### ISSUE TITLE
Add german language support

### ISSUE THREAD

**Issue by Nyhles** [League-of-Foundry-Developers/fvtt-module-polyglot#104]
I would like if polyglot would support german, therefore I can provide the lang\de.json file.

**Comment by mclemente** [comment]
Of course, I'd love it!
Be sure to read the translations' [README](https://github.com/League-of-Foundry-Developers/fvtt-module-polyglot/blob/master/lang/README.md) for the system specific translations, but don't sweat it if you don't play those systems or don't know the actual translations.

**Comment by Nyhles** [comment]
I can provide the lang\de.json translation but for the different settings I am lost.
The only one that I can help with is the DSA5 setting.

I am done with the de.json, where should I provide the file?

**Comment by mclemente** [comment]
You can just send it here or make a Pull Request if you know your way with Git (Fork this project > add lang/de.json > make a Pull Request).
