### ISSUE TITLE
Add DCC RPG system support

### ISSUE THREAD

**Issue by RKober2112** [League-of-Foundry-Developers/fvtt-module-polyglot#105]
**System Name:**
Dungeon Crawl Classics RPG

**System Repository or Foundry VTT address:**
https://github.com/foundryvtt-dcc/foundryvtt-dcc

**Does the system has the languages set up on Foundry?**
No

**Does the system uses languages as skills?**
No. 

**Additional context**
The System is a typical fantasy setting much like D&D. With much of the same languages, like Dwarf, Elvish, Common, Undercommon, Halfling, etc...

**Comment by mclemente** [comment]
I've managed to get the system's languages, but I don't see a way to add them to a character. Is there any way to do that?

**Comment by mclemente** [comment]
Nevermind, I've found it, the default player sheet didn't have the languages.
