### ISSUE TITLE
Custom Fonts, Set Custom Languages to a specific Font

### ISSUE THREAD

**Issue by RinVindor** [League-of-Foundry-Developers/fvtt-module-polyglot#106]
Pretty self-explanatory. It'd be great to be able to pick the font custom fonts use as well as insert our own custom fonts.

**Comment by JustinB555** [comment]
I didn't want to add another issue about custom fonts, but I think the option would be very cool. One of our DMs has a custom language with its own custom font. We looked at how we could add custom fonts to a custom language, but we hit a wall. Hope to see if this will be implemented.
