### ISSUE TITLE
Not seeing the following languages translate at all

### ISSUE THREAD

**Issue by TnTPiE** [League-of-Foundry-Developers/fvtt-module-polyglot#110]
**Describe the bug**
Logged in a GM or user and selecting the following languages from the drop down of available languages and they do not translate and are simply seen in plain text for all.. 

- Select Language
- Type Text
- Press Enter
- Language is seen without Translation

As a user with specific languages selecting the following languages from the drop down of available languages and they do not translate and are simply seen in plain text - so do users.  Languages that do not appear to translate are:

- Halfling
- Thieves Cant

Game Info:
 - Game System and version: D&D 5e
 - Hosted Foundry Server on the Forge : 0.7.9
 - Polyglot Version : 1.5.7.2
 - Are you using Babele? [No]

**Comment by mclemente** [comment]
I could not reproduce that bug. I've created a character that only speaks Common and another that only speaks Halfling and Thieves' Cant.

Were the messages sent as a character or as a GM? If the messages were sent as a GM, did you toggle the "Scramble on OOC chat messages" chat setting?

Common Speaker's POV:
![image](https://user-images.githubusercontent.com/5288872/114950661-ed7a6000-9e29-11eb-9105-6a3bb3df0795.png)
Halfling Thief's POV:
![image](https://user-images.githubusercontent.com/5288872/114950677-f2d7aa80-9e29-11eb-9881-d22d73688750.png)

**Comment by TnTPiE** [comment]
Good morning,

Thank you for the detailed response. I'll uninstall the module and restart the server then re-add. If it happens again, I will reproduce and post images too.

Thanks

**Comment by TnTPiE** [comment]
I have uninstalled the module, stop-start Foundry instance in Forge. Reinstalled the module and accessed the instance. Changed the language to Halfling on Polyglot and I'm still not getting this working. This is the view form the DM's side is saying 

![image](https://user-images.githubusercontent.com/82601628/114994343-98bfff00-9e94-11eb-87c9-667ec990c74b.png)

I've when logged into the same game as a player who can speak Halfling (validation):

![image](https://user-images.githubusercontent.com/82601628/114995123-682c9500-9e95-11eb-9beb-7e4c7564009e.png)

The same chat screen plus response:

![image](https://user-images.githubusercontent.com/82601628/114995549-db360b80-9e95-11eb-9459-f50dcc136f02.png)

Response in Thieve's Cant this time from the player who:

![image](https://user-images.githubusercontent.com/82601628/114995646-f6a11680-9e95-11eb-95c6-18265fac3653.png)

View of that response as the GM, and a response in Elvish:

![image](https://user-images.githubusercontent.com/82601628/114995846-25b78800-9e96-11eb-8035-78175fb2b814.png)

So I'm not sure if the module is loaded correct, or there is another issue behind the scenes as now none of the languages are working. Are there logs I can inspect?

**Comment by TnTPiE** [comment]
(facepalm)

So, you need to select a token to THEN choose an active language for it to work. Is this related to the OOC stuff?

**Comment by mclemente** [comment]
GMs that haven't selected a character have to enable the "Scramble on OOC chat messages" setting.
But that shouldn't be happening at all as a player. Players that have selected a character (on the menu that pops up when they login and haven't selected any) are supossed to be considered IC unless they spoke using `/ooc`. Otherwise, the only language shown on the selector would be Common.
Can you explain how you picked a language other than Common while not selecting a token as a player?

**Comment by TnTPiE** [comment]
Thank you @mclemente - that was the part of the manual I'd not read. I was joining as a player in the Forge, which I assume still has some element of the GM permissions. Retesting today, it doesn't appear to be happening now.
