### ISSUE TITLE
The actor could speak but doesn't read

### ISSUE THREAD

**Issue by patrickporto** [League-of-Foundry-Developers/fvtt-module-polyglot#117]
Hi
Recently I contributed to add the Shadow of The Demon Lord system. However, the system supports complex language structure like the following:

```json
data: {
    "read": false,
    "speak": true,
    "write": false
}
```

I am thinking if could encrypt the Journal though the chat log would be legible.

**Comment by mclemente** [comment]
I've implemented it, check it out!

**Comment by patrickporto** [comment]
It's working!

great job @mclemente
