### ISSUE TITLE
GM polyglot option in chat acting weird

### ISSUE THREAD

**Issue by Nedrapter** [League-of-Foundry-Developers/fvtt-module-polyglot#118]
I updated today the module to the latest version. When I type on chat as GM it picks automatically an actor (usually one of the actors I clicked previously but not the last one always) and it shows its languages only (instead of all options that rthe GM has). So practically I can't type anymore as GM.
Even if I switch to another scene that has only 5 player character and I select one of them, deselecting it, goes back to having selected an actor from another scene (e.g. a Goblin) and has only its languages available.
![image](https://user-images.githubusercontent.com/74311190/116006221-dcdc9d80-a612-11eb-873d-2818ab90c8a5.png)
Essentially, I can't type as GM anymore.

**Comment by mclemente** [comment]
Have you selected Goblin Commons through the Player Configuration by mistake? Because you're describing Foundry's default behavior (deselecting a token defaults to your character) and I haven't changed anything about that recently.

**Comment by Nedrapter** [comment]
You are indeed correct. I have no idea how was that selected since I never really had to click there as DM, but your trouble shooting was bullseye! Thanks!

**Comment by GabrielOsvair** [comment]
I had the same problem! It resolved by excluding goblin tokens that were copied for some strange reason.
