### ISSUE TITLE
Default language not working

### ISSUE THREAD

**Issue by Danii0206** [League-of-Foundry-Developers/fvtt-module-polyglot#121]
I'm using the system "Das schwarze Auge" (DSA). When I set the language "Garethi" as default in the module settings, the language selection dropdown disappears from above the chat-textfield. Console throws this error: 

Uncaught (in promise) TypeError: Cannot read property 'toLowerCase' of undefined
    at PolyGlot.updateUserLanguages (polyglot.js:300)
    at PolyGlot.setCustomLanguages (polyglot.js:594)

**Comment by mclemente** [comment]
Strange, I could not reproduce this bug. Does the bug persist after you reload the application?
Also, did you set Garethi as a Custom Language first? I'm not sure if its an actual DSA language or not, since it doesn't have the fonts set up.

**Comment by Nyhles** [comment]
I'll try to replicate it today in the afternoon.
Can you post screenshots of the Settings you used?

**Comment by Danii0206** [comment]
Yes, the bug persists after reload.

No I did not set Garethi as Custom Language, because it is an actual (the most common) language in DSA.
![Screenshot from 2021-04-28 15-33-56](https://user-images.githubusercontent.com/43935788/116412687-36bdad00-a837-11eb-8baf-1fd294cfaf3b.png)

I just set it as Default...
![Screenshot from 2021-04-28 15-29-51](https://user-images.githubusercontent.com/43935788/116412776-4c32d700-a837-11eb-8915-15c33b56b1d0.png)

... and the Language drop-down disappears.
![Screenshot from 2021-04-28 15-31-39](https://user-images.githubusercontent.com/43935788/116412843-5b198980-a837-11eb-8db1-d196733ca3fe.png)

**Comment by Nyhles** [comment]
I too could not replicate that error.
Garethi is set up in the modules/dsa5,json as a tongue, so the system uses the right font which it does as seen in screenshot 1

**Comment by Nyhles** [comment]
Adding to this, now I have been able to reproduce this error.
I forgot to reload foundry.

**Comment by Danii0206** [comment]
I edited the reload in my report above for easier replication instructions.

**Comment by mclemente** [comment]
Update and check if it still isn't working, I've made Garethi the default language for the system.

**Comment by Danii0206** [comment]
Thank you! :)
