### ISSUE TITLE
DSA: Isdira in JournalEntries

### ISSUE THREAD

**Issue by Danii0206** [League-of-Foundry-Developers/fvtt-module-polyglot#122]
System: DSA5

An Actor Setup with Language "Isdira" and Writing "Isdira- und Asdharia-Zeichen" can't read a JournalEntry written in Isdira.

**Comment by mclemente** [comment]
The character needs the Writing in Isdira to be able to read it. The module considers `Isdira- und Asdharia-Zeichen` and `Isdira` as completely different, same for `Asdharia`. Unfortunately, there isn't a way to set up the scripts to the languages that way.

**Comment by Nyhles** [comment]
Isdira is a language and Isdira- und Asdharia-Zeichen is the corresponding alphabet, you should use that one.

**Comment by Danii0206** [comment]
Isdira and Asdharia both use the same alphabet "Isdira- and Asdharia-Zeichen". If one could read something written in Isdira, but not in Asdharia... it is not possible to make that distinctino at the moment? In that case I'd suggest this as enhancement. ;)

I mean, like english and german use the same alphabet, but not everyone who knows latin letters can read german.

**Comment by Nyhles** [comment]
Rulewise they are both similar and therefore if you can read one, you can read the other one too.
Asdharia has just more ornaments

**Comment by Danii0206** [comment]
Nope, not every elf who can understand Isdira can understand Asdharia. Isdira evolved from Asdharia, like english evolved from anglo-saxon. True, some can, but most cannot read it.

**Comment by Nyhles** [comment]
Asdharia has RAW in the DSA5 ruleset the alphabet Isdira-Zeichen (although more ornamented) which means someone who can read one can read the other.
That's why the alphabet is called Isdira- und Asdharia-Zeichen.

However I might add Asdharia-Zeichen as own alphabet if you so desire.

**Comment by Danii0206** [comment]
No, that's not what I mean. Yes, they have the same alphabet. Like german and english, or Garethi and Bosparano have the same alphabet. But someone who only speaks Garethi cannot understand a text written in Bosparano. Or someone who only speaks english cannot read a text in german. The letters are the same, but the words don't make any sense.

**Comment by Nyhles** [comment]
Now I get what you are saying. I think thats not possible at the moment, however it could be an enhancement, but might be quite a lot of work, I don't know.

However, now that I testet it in journals, only alphabets are recognized even when your character knows the language that it is decoded in, eg. when something is decoded in garethi and not kusliker zeichen in a journal you wont be able to read it.

**Comment by Danii0206** [comment]
Thank you for patiently trying to understand me. :D

So this is not a bug, but a feature request. Got it. :)

**Comment by mclemente** [comment]
Hey, it's been a while.
I won't try to implement this anymore because it's too niche and would require a lot of work. The scrambling of letters doesn't make intelligible text (it uses numbers too) and I can't see how being able to "read" that will be useful.
