### ISSUE TITLE
Polyglot not working on item descriptions

### ISSUE THREAD

**Issue by gogrady4117** [League-of-Foundry-Developers/fvtt-module-polyglot#123]
I am unable to use polyglot when editing item descriptions.

**Comment by Nyhles** [comment]
I think that is intended?

**Comment by mclemente** [comment]
Polyglot only works for Journal entries, not items. Once you gave the item to a player, they would be able to translate the script.
A workaround would be to setup the text on a journal entry and link it in the item description.
