### ISSUE TITLE
Clicking "Save Update" in Chat Settings always reloads world

### ISSUE THREAD

**Issue by MrZwij** [League-of-Foundry-Developers/fvtt-module-polyglot#126]
**Describe the bug**
If you open Chat Settings in and click Save Update, the world always reloads regardless of whether any settings have been changed, and without warning.

**To Reproduce**
1. Open "Chat Settings" under Polyglot module settings
2. Click **Save Update**

**Expected behavior**
**If no chat settings changes have been made:** nothing.
**If chat settings changes have been made:** Wait until "Save Changes" has been clicked in the core "Configure Game Settings" window, then apply Polyglot changes and reload world if necessary.

 - Game System and version: **D&D 5e 1.2.4**
 - Polyglot Version: **1.5.17**
 - Are you using Babele? **No**

**Comment by mclemente** [comment]
Fixed on 1.5.18.
