### ISSUE TITLE
Replace system languages bug

### ISSUE THREAD

**Issue by Jmwhite45** [League-of-Foundry-Developers/fvtt-module-polyglot#129]
**Describe the bug**
So when I check the box to replace the system languages with my custom languages, nothing happens. When I have a number of custom languages in polyglot and I hit save changes(with Replace system languages **unchecked**). I see the additional languages added to the list of 5e languages(Like you should). HOWEVER, once I check the System Languages I will continue to see the 5e languages and my custom languages till I refresh the page. When I refresh the page, only the system languages will show up. I have tried various things and nothing works. I am doing this in a new world with the only polyglot installed so I know it's not a module conflict. 

**To Reproduce**
1. Create a foundry world for the 5e system
2. start/load world
3. activate PolyGlot
4. Open settings, Module settings, language settings, 
5. check "Replace system's Languages"
6. write "lan1,lan2,lan3,lan4,lan5" in custom languages
7. save changes, Save changes
8. Create new actor
9. edit Languages(Sees custom languages and system languages)
10. refresh page
11. open actor 
12. edit languages(Custom Languages are missing. System languages still appear)

**Expected behavior**
My expectation is that once I check the "Replace system Languages" button I will no longer see the 5e languages and only see the languages that I have under the custom languages

**Screenshots**
[https://imgur.com/a/XAKTnrY](https://imgur.com/a/XAKTnrY)
This screenshot shows you all the module settings I am using. Note if I refresh the page the custom languages will not appear on the languages list in the actor

**Versions**
 - Game System and version Foundry version 0.7.9, DnD5e - Fifth Edition System Version 1.52.4
 - Polyglot Version 1.5.17.2
 - Are you using Babele? No

**Additional context**
I am using Molten hosting to host the foundry server.

I did write a post on Reddit and followed most everyone's suggestions. That link is here: [https://www.reddit.com/r/FoundryVTT/comments/n3k4hl/polyglot_replace_system_languages_what_am_i/](https://www.reddit.com/r/FoundryVTT/comments/n3k4hl/polyglot_replace_system_languages_what_am_i/)

**Comment by Malagraves** [comment]
I am having an identical problem in Pathfinder 2E.
