### ISSUE TITLE
Hover text for POLYGLOT.LanguageLabel should show the DM which players would understand the chosen language

### ISSUE THREAD

**Issue by jcolson** [League-of-Foundry-Developers/fvtt-module-polyglot#131]
**Is your feature request related to a problem? Please describe.**
It would be nice for the DM to know which of his players speak the language (s)he's about to send to chat

**Describe the solution you'd like**
Hover text for `POLYGLOT.LanguageLabel` should show the DM which players would understand the chosen language

**Describe alternatives you've considered**
Maybe hover over the `select name='polyglot-language'`?

**Additional context**
Maybe rifle through `game.actors.entries` and create a hover that consists of `actor.data.data.traits.languages.value` and `player.name` ...

**Comment by mclemente** [comment]
I'll hold on implementing this until 0.8 is out (ETA end of May) since I've already got a working version for 0.8 and this might not work out the same way as on 0.7.9.

**Comment by mclemente** [comment]
Hovering over the Language label would be a bit hard because I would need to write a new function just for that.
What I did was to add a `title` tag on the selector's options for the GM that will show `PCs that know [language]: list of characters`.
