### ISSUE TITLE
Rune Issue

### ISSUE THREAD

**Issue by Tam1974** [League-of-Foundry-Developers/fvtt-module-polyglot#132]
When a Character uses a language that another Character cannot understand, instead of the usual Runes, I get scrambled English keyboard text

Example
My Gnome speaks in Gnomish - "Hello"
Player 2 Orc cannot speak Gnome, so sees - "G7FD9" - normally, (before the latest update), this would have been in Runes.

To Reproduce - 
Just use Polyglot

Tried reinstalling - still same.

Worked fine before update.

 - Game System and version D&D 5e 1.2.4
 - Polyglot Version 1.5
 - Foundry 0.7.9
 - Are you using Babele? [No]

**Comment by mclemente** [comment]
Hello, I was unable to reproduce this on 1.5.18.1.
I'm working on supporting FVTT 0.8 release and I couldn't reproduce that bug there either. With 0.8 coming in about a week, I suggest you to downgrade to an [earlier version](https://github.com/League-of-Foundry-Developers/fvtt-module-polyglot/releases) until 0.8 is out of beta.

**Comment by Tam1974** [comment]
Many thanks for your reply.  I will try downloading an earlier version.

**Comment by EsdinDev** [comment]
Hi. I've the same problem.

To Reproduce -
Create a Journal entry with some text > Select all text > Go to Format menu > Go to Polyglot > Select "elfic" > Save the journal > Click on the "Runes" button on the top of the journal window.

You will see the text as comented @Tam1974.

Tried reinstalling -
Yes, still the same.

Can use a before version? -
No, my version are managed by Bazaar on Forge.

Working environment:

- Foundry VTT version: 0.7.9
- Game System and version: DnD5e 1.2.4
- Polyglot version: 1.5
- Are you using Babele? No

**Comment by Tam1974** [comment]
Your new update seems to have solved the issue - many thanks

**Comment by brucetony** [comment]
I had this error as well, but 1.5.18.2 appears to have fixed it thanks!
