### ISSUE TITLE
No language without selecting token first

### ISSUE THREAD

**Issue by LorduFreeman** [League-of-Foundry-Developers/fvtt-module-polyglot#133]
**Describe the bug**
Players need to have their token selected to actually speak in their available languages despite having them as options in the language dropdown menu at all times.

The player's token needs to be selected to properly speak in a language - it would be more practical if this worked without a selected token as well (since every player has at least one main character owned).

**Addendum**
After restarting talking in a language without a selected token seems to work, but one issue remains: The token still needs to be on the current scene to work. Is this intended?

D&D 5e 1.2.4
Foundry 0.7.9
Polyglot  1.5.18.1

Are you using Babele? No

**Comment by mclemente** [comment]
Have your players selected a character? It's automatic if they do.
![image](https://user-images.githubusercontent.com/5288872/118677535-af7aae00-b7d2-11eb-8dce-3397f2e5df54.png)

**Comment by LorduFreeman** [comment]
They have, and I need to correct myself: It works if there's no token selected but not if there is no token on the map.

**Comment by mclemente** [comment]
I see. It's "intended" as Foundry considers a user without a token on the map as talking Out of Character.
I'll change the `Scramble on OOC chat messages` setting from being binary to a choice between [All, GM, Players, None].

**Comment by mclemente** [comment]
Bear in mind, this change will only be available on Foundry 0.8, since it's coming within the next weeks.
