### ISSUE TITLE
Request for Dark Heresy

### ISSUE THREAD

**Issue by Nosferaschu** [League-of-Foundry-Developers/fvtt-module-polyglot#135]
**System Name:**
Dark Heresy 2nd Edition (dark-heresy)

**System Repository or Foundry VTT address:**
https://github.com/moo-man/DarkHeresy2E-FoundryVTT

**Does the system has the languages set up on Foundry?**
Id don't think it does

**Does the system uses languages as items?**
No, languages are skills.

**[Optional] If it isn't straightforward, how do I add a language to a character?**
exept for Low Gothic, you need to add the skill.

**Additional context**
The common tonge is Low Gorhic, every peron in the imperium of man speaks low gothic and in the game can read/write it. So it is not needed to have the low gothic skill, in this special case the skill is used for dialects or comlicated text ect. For every other language, the skill needs to be at least "Known" to be able to read/write/speak the language

**Comment by mclemente** [comment]
I"ll have to wait for it to get updated to 0.8 before I can support it (some of its features are broken for me).
Also, how do I add skills to the game? They don't show up on the Item Directory.
Is there a pattern for the name of the languages (e.g. `Language (Low Gothic)`)?

**Comment by Nosferaschu** [comment]
skills are hard implemented in the game in the template.json and can be used in macros with 
```
actor.data.data.skills.linguistics.specialities["highGothic"];
```
in the sheet they can be skilled under advances 
![linguistics](https://user-images.githubusercontent.com/84198011/119882560-d81b4a00-bf2e-11eb-8494-257b9ebbc666.PNG)

**Comment by mclemente** [comment]
I found out there was a 0.8 branch which I managed to use.
Version 1.6.3 works with Dark Heresy, but some languages don't have fonts set up because I don't know much about the lore, so feel free to play around with what looks better for each and I'll change it later.

**Comment by Nosferaschu** [comment]
i have to wait for stable release, but then i will look into it and find the right fonts =) many thanks even if i cant use it right now, i will use it with stable 8.x
