### ISSUE TITLE
Savage Worlds Adventure Edition

### ISSUE THREAD

**Issue by FloRad** [League-of-Foundry-Developers/fvtt-module-polyglot#136]
**System Name:**
Saage Worlds Adventure Edition

**System Repository or Foundry VTT address:**
https://foundryvtt.com/packages/swade

**Does the system has the languages set up on Foundry?**
Not that I can see

**Does the system uses languages as items?**
Yes

**[Optional] If it isn't straightforward, how do I add a language to a character?**
Languages are skill items so adding a new skill and naming it after the Language should be all you need

**Additional context**
Savage Worlds is a system with no set languages as it is a generic game system without a singular setting. Thus it might be a good idea to add some sort of way to let modules add language definitions on the fly by moving the config jsons into memory

**Comment by mclemente** [comment]
SWADE is already supported, Polyglot gets the character's languages as long as they follow the `Language (Name)` pattern.
To add a language as a GM, just add custom languages. If you also want fonts, save, go back to the settings and then click the Language Settings button.
