### ISSUE TITLE
Matching Words and Rune

### ISSUE THREAD

**Issue by PVTRAN** [League-of-Foundry-Developers/fvtt-module-polyglot#138]
Testing around with Polyglot, I notice that the letter while may have matching rune but if you create a word out of it, it's ignore matchings lettesr and just use the different rune. I don't know if this is intent that but if possible can we have it so that each letter in a word has it own matching Rune? 

![image](https://user-images.githubusercontent.com/60622516/120514000-d0c6c700-c39a-11eb-834f-e10ecd039c64.png)

**Comment by mclemente** [comment]
It is intended, it is complete RNG.

Making characters use the same rune on different words: possible.
Making runes unique to those letters: impossible.

There's only 62 possible runes (numbers + upper/lowercase letters), so you'll still get repeated runes for different characters (e.g. `1` and `b` might use the same rune).

Example: `E` and `S` have the same rune of `1` and `)`, respectively.
![image](https://user-images.githubusercontent.com/5288872/120598917-3bb8e200-c41d-11eb-9ca5-8bb662053ef2.png)
