### ISSUE TITLE
Allow Polygot to function in item descriptions

### ISSUE THREAD

**Issue by OrangeJelly-glitch** [League-of-Foundry-Developers/fvtt-module-polyglot#144]
I am running a PF2e game and I have been trying to add books to the game in another language as an item. The closest solution I have found is to make a journal entry that the item links to. Sadly, for this to function the PC with the book within their inventory must have the observer permission for the journal entry. The issue with this is that I have to allow the journal entry to be viewable and this allows them to see the structure of my journal folders and they can view this journal without the item in their inventory. If Polygot were to function within the item descriptions I could functionally make books/notes to leave around my maps.

**Comment by mclemente** [comment]
It can't be done. The owner of the item can edit it even if they don't know the language, and the text loses its script once it's being edited.
Example:
1) make a Journal and write something in a language, then click the rune button so you see the script.
2) Give owner perm to a player
3) Log in as that player and check the journal.
4) Edit it.

As for your folder problem, maybe make a new folder just for books?
