### ISSUE TITLE
System Das Schwarze Auge / The dark eye won't work

### ISSUE THREAD

**Issue by kaspagious** [League-of-Foundry-Developers/fvtt-module-polyglot#145]
After an recent update of the polyglot (to vers. 1.6.6) and the Das Schwarze Auge module (to vers. 2.03) a new bug emerged. 
The language of the selected actor are not found properly. 
Most likely the matching of the regular expression line 273 to 274 inside /module/logic.js is outdated and doesn't work properly.

**Comment by mclemente** [comment]
Thank you for reporting it. It's fixed now.
