### ISSUE TITLE
Default language selection only works when name of language is typed in lower case

### ISSUE THREAD

**Issue by cdstephens** [League-of-Foundry-Developers/fvtt-module-polyglot#146]
When typing in the default language, the selection is not recognized unless the language name is typed in all lower case. 

Edit: I found one additional bug with regards to default languages, I will describe it at the bottom. 

Foundry version: 0.8.6
System: DnD 5e, version: 1.3.3
Polyglot version: 1.6.7

Reproduction: 
1. Create a new world with DnD 5e system
2. Load Polyglot
3. In module settings, type "Goblin" as the default language

Result: Typing a message in Goblin will result in runic symbols and a translation rather than plain text. 

Workaround: Type "goblin" as the default language and it works as expected. 

Additional bug: If I add a custom language (such as "New Language"), to properly set it to default it must be in all lower case in the default language field (e.g. "new language"). If I check "replace system's languages" and leave the default languages field blank, it will output the default language in runes and translation, not plaintext as expected. This is **especially** a problem given that by default, every player's module configuration will have the default languages field blank, meaning they have to manually set their default language.

**Comment by mclemente** [comment]
Thanks for reporting it. Both bugs were caused by the same line of code, so fixing one fixed the other.

**Comment by cdstephens** [comment]
Thanks for working on this! I can confirm that the first bug was fixed, however, the second bug regarding "replace system's languages" is not completely fixed. I'll write up reproduction steps etc. in case it helps clarify things. Or perhaps my settings are incorrect? 

Bug: When using "Replace System's Languages", the first language is not set to the default language automatically. 

Foundry version: 0.8.6
System: DnD 5e, version: 1.3.5
Polyglot version: 1.6.8

Reproduction:

1. Create a new world with the DnD 5e system
2. Load Polyglot
3. In module settings, type "Vulkan" in Custom Languages and click on the checkbox for "Replace System's Languages"
4. Leave the Default Language field blank 
5. Type in Vulkan (the only allowed language) in the chat

Result: Typing a message in Vulkan will result in runic symbols and a translation rather than plain text.

Workaround: Set Vulkan to be the Default Language manually by typing "Vulkan" in the Default Language field. 

Thank you again for the quick replies and for working on the module!

**Comment by mclemente** [comment]
Sorry about that, the Custom Language + Default Language (without Replace Languages) had a bug similar to the first and I got it mixed with the additional one.
I think I got it now: the defaultLanguage() function was only taking into account that the languages were an Array, not a Set.

**Comment by cdstephens** [comment]
Works for me now; thanks again! I look forward to using this module in my upcoming games.
