### ISSUE TITLE
Shadowrun 5e Support

### ISSUE THREAD

**Issue by Eskatonion** [League-of-Foundry-Developers/fvtt-module-polyglot#150]
I love the module and was hoping for shadowrun 5e support. There is a community module for this system, which supports languages but does not have a default language pack installed. When trying to use with this system, Polyglot is able to pull some, but not all languages found on character sheets. The languages that it pulls may actually be from an alternative source as it seems to pull languages that are not included on any character sheet in game.

**Comment by mclemente** [comment]
Link to the community module? There's none on Foundry's list. Otherwise I can't do anything.

**Comment by Eskatonion** [comment]
I'm sorry about that, I've just returned from a camping vacation and saw this reply. The community module is here: https://foundryvtt.com/packages/shadowrun5e if too late that's OK, thanks for the great add on anyway!

**Comment by mclemente** [comment]
Oh, "module" threw me off and made me think there was an actual module (not a system) that added the languages.
