### ISSUE TITLE
Comprehend Languages Spell

### ISSUE THREAD

**Issue by ErebusAres** [League-of-Foundry-Developers/fvtt-module-polyglot#155]
**Is your feature request related to a problem? Please describe.**
If I use the Comprehend Languages spell, I should be able to read or understand any spoken language.

**Describe the solution you'd like**
If there isnt a way already, add some kind of Comprehend Effect Toggle or something like that.

**Describe alternatives you've considered**
Some kind of checkbox or DM toggle, maybe?

**Additional context**
If this is already implemented. Add some kind of info to the wiki, please!

**Comment by filhit** [comment]
As a native foundry workaround, you can create an effect, that would give the actor all the languages. 

Example for dnd5e system:
Create a "Comprehend languages effect".
Set `data.traits.languages.value` to override with
```
["common", "aarakocra", "abyssal", "aquan", "auran", "celestial", "deep", "draconic", "druidic", "dwarvish", "elvish", "giant", "gith", "gnomish", "goblin", "gnoll", "halfling", "ignan", "infernal", "orc", "primordial", "sylvan", "terran", "cant", "undercommon"]
```

**Comment by mclemente** [comment]
The character's info wasn't updating correctly when Active Effects were applied.

Follow this guide to set it up correctly: https://github.com/League-of-Foundry-Developers/fvtt-module-polyglot/wiki/%5BD&D5e%5D-Active-Effects-and-Comprehend-Languages-&-Tongues
