### ISSUE TITLE
Cannot see languages in UESRPG

### ISSUE THREAD

**Issue by 95Gman** [League-of-Foundry-Developers/fvtt-module-polyglot#156]
**Describe the bug**
No languages appear in the list for the DM.

**To Reproduce**
1. Uninstall Polygot.
2. Reinstall Polygot and enable in UESRPG world
3. Cannot see Languages as DM.

**Expected behavior**
As DM, see all available languages.

**Screenshots**
![image](https://user-images.githubusercontent.com/74572009/126096326-b732d29e-4844-49b2-a63d-c0880c7743ae.png)

 - Foundry 0.8.8. UESRPG 1.33
 - Polyglot Version 1.7.2
 - Are you using Babele? No

**Additional Info**
Prior to a reinstall of Polygot, Dovah had missing characters. That's a secondary bug.

**Comment by 95Gman** [comment]
Was an idiot and left the 'replace system language' on.

**Comment by mclemente** [comment]
Thanks for reporting it. It should be fixed now.

**Comment by 95Gman** [comment]
The latest patch has caused this error again.
