### ISSUE TITLE
Dovah Language has missing characters

### ISSUE THREAD

**Issue by 95Gman** [League-of-Foundry-Developers/fvtt-module-polyglot#157]
**Describe the bug**
Missing characters and the text goes off-screen instead of wrapping.

**To Reproduce**
1. Boot up UESRPG with Polygot
2. Type in Dovah

**Expected behavior**
No missing characters in Dovah

**Screenshots**
![image](https://user-images.githubusercontent.com/74572009/126102575-0586c7e3-c88d-4cb7-91ff-804fba00f909.png)

 - Foundry 0.8.8 UESRPG 1.33
 - Polyglot Version 1.7.2.1
 - Are you using Babele? No

**Comment by mclemente** [comment]
I've made a mistake and added this font, which doesn't have 0-9 characters. I've found a replacement and will be fixed on the next update.
