### ISSUE TITLE
Custom languages no longer appear in the actor sheet (5e)

### ISSUE THREAD

**Issue by DarKDinDoN** [League-of-Foundry-Developers/fvtt-module-polyglot#158]
**Describe the bug**
With the latest version of polyglot, the config remains OK but the custom languages are not longer displayed in an actor sheet

**To Reproduce**
1. Add whatever special language
2. Remove basic 5e languages
3. Open up an actor sheet
4. The created special language doesn't appear in the language selection window

**Expected behavior**
The list of selectable languages should display all the specials (custom) languages

**Screenshots**
![image](https://user-images.githubusercontent.com/1687854/126124872-870c1fa1-7594-4649-87c2-db44f66670ab.png)

 - Game System and version: D&D 5e 1.3.6
 - Polyglot Version: 1.7.2.1
 - Are you using Babele? Yes

JS Error, might not be related
![image](https://user-images.githubusercontent.com/1687854/126125047-689954aa-702a-45a9-b81f-a260818913b4.png)

**Comment by mclemente** [comment]
Thanks for reporting it, it should be fixed now.
