### ISSUE TITLE
Language tab does not open in UESRPG

### ISSUE THREAD

**Issue by 95Gman** [League-of-Foundry-Developers/fvtt-module-polyglot#159]
**Describe the bug**
List of languages is broken.

**To Reproduce**
1. Start up UESRPG system with Polygot

**Expected behavior**
See list of languages

**Screenshots**
![image](https://user-images.githubusercontent.com/74572009/126160737-64f66afa-0029-46ae-a8a1-3497b0d38b4b.png)

 - Foundry 0.8.8 UESRPG 1.33
 - Polyglot Version 1.7.3
 - Are you using Babele? No

**Comment by mclemente** [comment]
Should be fixed now. Thank you!
