### ISSUE TITLE
Polyglot doesn't work at all and throws errors in console

### ISSUE THREAD

**Issue by Berytak** [League-of-Foundry-Developers/fvtt-module-polyglot#160]
Console throws the following Error whan clicking on an actor
>VM4460:8 TypeError: Cannot read property 'split' of null
>   at dnd5eLanguageProvider.getUserLanguages (LanguageProvider.js:133)
>    at Polyglot.getUserLanguages (logic.js:120)
>    at Polyglot.updateUserLanguages (logic.js:146)
>    at Polyglot.controlToken (logic.js:68)
>    at Function._call (eval at <anonymous> (listeners.js:56), <anonymous>:4:14)
>    at Function.callAll (foundry.js:153)
>    at Token5e.control (foundry.js:18874)
>    at Token5e._onClickLeft (foundry.js:19088)
>    at Token5e._onClickLeft (foundry.js:45672)
>    at x.🎁call_wrapped [as call_wrapped] (libWrapper-wrapper.js:465)

This is shown in the chat windows pulldown menu. This char can speak "Common, Infernal, and Goblin" but the list is empty.
![image](https://user-images.githubusercontent.com/85394657/126179645-ce97e91d-53c8-4d85-baf0-4040bdcb03f1.png)

And it also leads to not showing anything in the journal if you have "Monk's Enhanced Journal" installed. Search, show and edit button don't work either.
![image](https://user-images.githubusercontent.com/85394657/126180877-a8978ca6-60c7-4ebc-8afc-6f3e4bf7a16e.png)

The top two issues persist even when disableing the journal module.
All software, modules and systems are on the latest version.

**Comment by mclemente** [comment]
That error was somehow caused by a Special Language (the ones you input into the character sheet). Couldn't reproduce the error because I might have fixed it when working on another issue.
That Monk's Enhanced Journal problem is due to it trying to run code that was changed on the update, I'll send Ironmonk a fix soon.

**Comment by Berytak** [comment]
Thanks for narrowing down the problem. It seems that NPCs that have been importet via MrPrimates D&D Beyond importer cause this problem. This is the language information a commoner has for example:
![image](https://user-images.githubusercontent.com/85394657/126202256-51dc1c04-811b-435f-96e2-0cb47ada7a45.png)

After deleting the "Any one language (usually Common)" phrase it works on this campain. Sadly I've tried this in another campaign and it didn't work. I've delete all actory except the player characters. I've double checked the languages but there was nothing special, or manually added.

Nevertheless, it's good to hear that the Monk modules get a fix...

**Comment by Zamrod** [comment]
I'm definitely having this issue in 1.7.3.1 in DnD5e. The language list is blank for all tokens and that same error shows up in the console:

VM14898:8 TypeError: Cannot read property 'split' of null
    at dnd5eLanguageProvider.getUserLanguages (LanguageProvider.js:132)
    at Polyglot.getUserLanguages (logic.js:120)
    at Polyglot.updateUserLanguages (logic.js:146)
    at Polyglot.controlToken (logic.js:68)
    at Function._call (eval at <anonymous> (listeners.js:56), <anonymous>:4:14)
    at Function.callAll (foundry.js:153)
    at Token5e.control (foundry.js:18874)
    at Token5e._onClickLeft (foundry.js:19088)
    at Token5e._onClickLeft (foundry.js:45672)
    at x.🎁call_wrapped [as call_wrapped] (libWrapper-wrapper.js:465)

**Comment by revilowaldow** [comment]
Same errors here as others are having in dnd5e.
Completely non-functional

![image](https://user-images.githubusercontent.com/52298102/126204709-1bb251e5-e3d3-4239-ba55-d3ca7c8ea1b5.png)


![image](https://user-images.githubusercontent.com/52298102/126204687-0a5b26a5-eb7e-480e-813f-3a413feb4f94.png)

**Comment by revilowaldow** [comment]
> It seems that NPCs that have been importet via MrPrimates D&D Beyond importer cause this problem. 

The problem is because Polyglot isn't handling the contents of a free text field properly. The issue is therefore with Polyglot.
Whether what is in the field was put there by the user or by a module, Polyglot needs to be able to handle it.
