### ISSUE TITLE
Errors in console

### ISSUE THREAD

**Issue by kristianserrano** [League-of-Foundry-Developers/fvtt-module-polyglot#161]
**Describe the bug**
Polyglot is throwing repeated errors.

![Screen Shot 2021-07-19 at 7 43 03 PM](https://user-images.githubusercontent.com/1796189/126241418-757e127b-b51b-480a-930c-81160fcbcdbd.png)

**To Reproduce**
I haven't done anything other than update.

**Expected behavior**

**Screenshots**

 - SWADE 0.23.3
 - Polyglot Version 1.7.3.2
 - Are you using Babele? No

**Comment by mclemente** [comment]
I forgot SWADE didn't have languages set up, so it is trying to load a variable that wasn't set. Will be fixed soon.
