### ISSUE TITLE
Custom alphabet not saving

### ISSUE THREAD

**Issue by ToyoTrueno** [League-of-Foundry-Developers/fvtt-module-polyglot#162]
**Describe the bug**
Polyglot no longer saves custom alphabets/fonts on languages when you log out and log back in, returning to the system default.

**To Reproduce**
1. Go to polyglot language settings
2. Change a language's alphabet
3. Save changes
4. Log out and log back in

**Expected behavior**
When I save my new alphabets to a language, I expect it to save instead of resetting back to defaults.

**Screenshots**
![01](https://user-images.githubusercontent.com/60529730/126244160-12a8247b-ddae-47ec-9522-02f170f2f6b4.PNG)
![02](https://user-images.githubusercontent.com/60529730/126244169-fc5e7a89-b407-433b-8442-e3bfab616f47.PNG)
![03](https://user-images.githubusercontent.com/60529730/126244173-ce15fb9f-944f-4564-9381-3c899ef6d8be.PNG)
![04](https://user-images.githubusercontent.com/60529730/126244176-f65b3d35-ed00-4cb2-bb81-2f17ab6d68e4.PNG)
![05](https://user-images.githubusercontent.com/60529730/126244185-f7ddbfb9-c196-4524-92d2-ed08e8166be2.PNG)

**Versions**
 - DnD5e 1.3.6
 - Polyglot 1.7.3.2
 - Foundry 0.8.8
 - Not using Babele

**Comment by mclemente** [comment]
I'm so sorry, it's fixed now. Thank you for reporting it!
