### ISSUE TITLE
SWADE Languages aren't being overwritten

### ISSUE THREAD

**Issue by kristianserrano** [League-of-Foundry-Developers/fvtt-module-polyglot#163]
**Describe the bug**
I had a list of custom languages added to Polyglot, but the Language Settings panel now has a dropdown for "Generic Savage Worlds Adventure Edition" and doesn't list the names of the languages I've added below that.

**To Reproduce**
1. Add Custom Languages
1. Open the Language Settings
1. See languages missing

**Expected behavior**
I expected to see the list of languages I entered. I'm also surprised that SWADE has a "provider" given that it's a setting agnostic system. The languages would be setting specific, which is why the custom languages are ideal.

**Screenshots**

![Screen Shot 2021-07-19 at 9 06 51 PM](https://user-images.githubusercontent.com/1796189/126246887-2946657c-77ff-4703-ab9f-752ac2a37bc1.png)

 - SWADE v0.20.3
 - Polyglot v1.7.3.2
 - Are you using Babele? No

**Comment by mclemente** [comment]
Have you tried Reset Defaults? They show up if you do. That's not intended, though, so it will be fixed.
As for the SWADE Provider, its only function currently is to get characters' languages, since I separated system-specific code from the system-agnostic code.
