### ISSUE TITLE
Languages to be written in item cards

### ISSUE THREAD

**Issue by 95Gman** [League-of-Foundry-Developers/fvtt-module-polyglot#164]
**Is your feature request related to a problem? Please describe.**
Currently cannot use polygot languages in item card descriptions within UESRPG.

**Describe the solution you'd like**
Polygot functionality in item cards within UESRPG.

**Comment by mclemente** [comment]
That's not actually supported by Polyglot. See https://github.com/League-of-Foundry-Developers/fvtt-module-polyglot/issues/123
