### ISSUE TITLE
Settings - previous configuration is lost

### ISSUE THREAD

**Issue by DarKDinDoN** [League-of-Foundry-Developers/fvtt-module-polyglot#165]
**Describe the bug**
With the latest release, my custom language settings (fonts) are gone. I need to make to re-map all languages to the correct fonts.

**To Reproduce**
Not sure. Creating custom languages and map them to fonts before updating to the latest version?

**Expected behavior**
Is this normal?

**Also**
If the checkbox "Replace System's Languages", is it possible not to have the system languages in the "Language Settings" window?

- FVTT: 0.8.8
 - Game System and version: dnd5e 1.3.6
 - Polyglot Version: 1.7.3.4
 - Are you using Babele? Yes

**Comment by mclemente** [comment]
Yes, there was a bug that wasn't saving the fonts properly. I'm really sorry.

**Comment by DarKDinDoN** [comment]
@mclemente no worries. That happens.
Glad you keep that module up to date 😃
