### ISSUE TITLE
GM cannot see any languages in chat window dropdown

### ISSUE THREAD

**Issue by sebbosaurus** [League-of-Foundry-Developers/fvtt-module-polyglot#166]
Hi,

I've tried deactivating all other modules and this still persists. When I log in as a player, the dropdown lists the player character's known languages and works as intended. However, As the GM, there are no language options in the drop-down, regardless of whether I've selected a token or not. I have scramble OOC messages set to GM only.

Thanks ahead of time for any and all help.

**Comment by mclemente** [comment]
Which system are you on?

**Comment by sebbosaurus** [comment]
Pathfinder 2e - sorry I forgot to mention!

**Comment by mclemente** [comment]
You don't even see your players' languages?
Have you enabled the Replace Languages setting? You and your players would see their characters' languages, even if replaced, but you wouldn't see anything on the box otherwise.

**Comment by dd8630** [comment]
I have the same issue. I'm used the PF2 system, and Polyglot has worked fine. I guess there was a recent update that broke it - the dropdown menu is just blank. The languages display properly for players, but on the GM side it's blank.

**Comment by sebbosaurus** [comment]
> You don't even see your players' languages when selecting their tokens?
> Have you enabled the Replace Languages setting? You and your players would see their characters' languages, even if replaced, but you wouldn't see anything on the box otherwise.

No, I don't have that setting enabled.

**Comment by mclemente** [comment]
Could any of you zip your world file and send it to me? I can't reproduce this on a blank world for some reason.

**Comment by sebbosaurus** [comment]
[ForgeVTT-export-stp-222-2021-07-22_21_4_21.zip](https://github.com/League-of-Foundry-Developers/fvtt-module-polyglot/files/6865216/ForgeVTT-export-stp-222-2021-07-22_21_4_21.zip)

Here ya go! Thank you for your efforts so far

**Comment by mclemente** [comment]
It seems Minions are the culprit, because they don't have languages set up, I'll make a fix.
