### ISSUE TITLE
No language selection dropdown menu for GM?

### ISSUE THREAD

**Issue by CommanderAlex98** [League-of-Foundry-Developers/fvtt-module-polyglot#167]
FVTT 0.8.8
Polyglot 1.7.3.5
Gamesystem DSA/TDE 2.1.0

I can only choose a language, if I click on a token as GM. The language selection dropbox shows no languages with no selected token. (Scramble OOC Messages is activated GM only).

![image](https://user-images.githubusercontent.com/61950984/126744140-4ca8d2cf-a646-4480-b524-0c521c31ccc2.png)

**Comment by mclemente** [comment]
Any errors on the console (F12)?
You have the Core Rules module, right? Otherwise you won't see any, except the ones you've added as Custom Languages.
I haven't been following DSA updates, does the Core Special Abilities compendium still have Languages there? Are they still named `Language (X)` and `Script (X)`?

**Comment by CommanderAlex98** [comment]
![image](https://user-images.githubusercontent.com/61950984/126762248-ef4a4fcc-4b94-45a0-91d6-59b8880046b9.png)

Yeah, Core Rules Module is installed. The Core Special Abilities compendium has still the languages inside. 
![image](https://user-images.githubusercontent.com/61950984/126762435-23aa6ad6-cbea-4747-b6ff-145698c85a2b.png)

**Comment by CommanderAlex98** [comment]
When I select a token, it's still possible to choose their language
![image](https://user-images.githubusercontent.com/61950984/126762778-0c87e08f-40e7-4c9e-b43c-1a47f726579e.png)

**Comment by CommanderAlex98** [comment]
Releasing the token, the globe symbol in the chat message turns into red
