### ISSUE TITLE
Players don't understand languages without token on the scene.

### ISSUE THREAD

**Issue by szefo09** [League-of-Foundry-Developers/fvtt-module-polyglot#171]
**Describe the bug**
Players and GMs don't understand languages without token on the scene.

**To Reproduce**
1. Write something in any language (Common f.e.)
2. Remove player's token from active scene.
3. Login as the player.
4. Even if the player character knows Common, they don't understand anything in chat until you place their token on the scene.

**Expected behavior**
Players should be able to read the message even if they have no characters on the current scene.

 - Game System and version D&D5e 1.3.6
 - Polyglot Version 1.7.3.6
 - Are you using Babele? No

**Comment by mclemente** [comment]
Yeah, the function that got a character's languages was triggered when its token was loaded, so when messages were loaded right after, the player didn't have any known languages. Should be fixed now.
