### ISSUE TITLE
Warhammer Fantasy Roleplay 4e languages

### ISSUE THREAD

**Issue by nottsknight** [League-of-Foundry-Developers/fvtt-module-polyglot#173]
**Describe the bug**
No languages appear in the dropdown list when using Polyglot with Warhammer Fantasy Roleplay 4th Edition. Unsure whether this is because WFRP isn't supported, or because of a bug.

**To Reproduce**
1. Observe the dropdown list.

The dropdown remains empty even if a series of custom languages, and even if the replace system's languages checkbox is on.

**Expected behavior**
A list of all system languages (Reikspiel, Elthárin, etc.) should be available to select in the dropdown.

**Screenshots**

 - wfrp4e 4.0.5
 - Polyglot 1.7.5
 - Are you using Babele? No

**Additional context**
As mentioned, unsure if this is because of a bug or because WFRP isn't supported.

**Comment by mclemente** [comment]
It's actually supported, I've made a typo ("wfrp4" instead of "wfrp4e") so it isn't loading properly right now.
It'll get fixed shortly.

**Comment by nottsknight** [comment]
Super! Thanks so much :)
