### ISSUE TITLE
Can't update

### ISSUE THREAD

**Issue by Fridan99** [League-of-Foundry-Developers/fvtt-module-polyglot#174]
**Describe the bug**
It's impossible to update, it gest a message: not provide a valid manifest file. 

**To Reproduce**
1. Try to update.

**Screenshots**

![1](https://user-images.githubusercontent.com/86131373/127402447-4671f63e-4979-4a4b-b549-8ceafdf01b6f.jpg)

 - Game System and version [dnd5e 1.4.1]
 - Polyglot Version [e.g. 1.7.5]
 - Are you using Babele? [No]
 - Foundry version [0.8.8]

I don't know if it's an error itself ... but I'll leave it here just in case.

**Comment by mclemente** [comment]
That's weird, I haven't changed the module.json file at all. Just try updating it later, I guess.

**Comment by Fridan99** [comment]
Now it has just updated me. It's strange... well I guess everything is ok. :)
