### ISSUE TITLE
UESRPG update

### ISSUE THREAD

**Issue by 95Gman** [League-of-Foundry-Developers/fvtt-module-polyglot#176]
**System Name:** 
UESRPG d100

**System Repository or Foundry VTT address:**
https://gitlab.com/DogBoneZone/uesrpg-3e

**Does the system has the languages set up on Foundry?**
Yes

**Does the system uses languages as items?**
Yes, they are their own entities as of version 1.34

**[Optional] If it isn't straightforward, how do I add a language to a character?**
Language category on main page.

**Additional context**
Instead of having a skill called Language (Language) we now have a language section. Instead of polygot reading Language (Language) skill, it should now look for Language under the language section.
The provided zip is the beta release. The language section is safe to work with.
[uesrpg-d100.zip](https://github.com/League-of-Foundry-Developers/fvtt-module-polyglot/files/6910539/uesrpg-d100.zip)

**Comment by mclemente** [comment]
Thanks, I'll update it soon.
Hint:
On actor.js `_preCreate`, add the following inside ` if (data.type === "character") {` for their tokens to be linked to characters by default:
```js
this.data.token.update({vision: true, actorLink: true, disposition: 1});
```
