### ISSUE TITLE
Polygot not appearing in item card tinyMCE (UESRPG d100)

### ISSUE THREAD

**Issue by 95Gman** [League-of-Foundry-Developers/fvtt-module-polyglot#179]
**Describe the bug**
Cannot use polygot in item cards

**To Reproduce**
1. Load UESRPG d100
2. Create an item, any item
3. Open the drop down menu where 'Paragraph' is. There is no polygot function

**Expected behavior**
Polygot functionality in item cards.

**Screenshots**
![image](https://user-images.githubusercontent.com/74572009/127795180-a1c816f3-55c5-4e92-bb34-774fb7093adb.png)

 - Foundry 0.8.8. UESRPG d100 1.34
 - Polyglot Version 1.7.6.4.2
 - Are you using Babele? No.

**Comment by mclemente** [comment]
Polyglot only works with journals. The owner of the item can circumvent the language.
