### ISSUE TITLE
Accurate characters

### ISSUE THREAD

**Issue by 95Gman** [League-of-Foundry-Developers/fvtt-module-polyglot#180]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Characters in polygot are randomized. If I type A B C, it will appear as C G D (This is an example). I'd like the characters of the polygot languages to not be scrambled, and represent their actual character. A B C = A B C.

**Describe alternatives you've considered**
None.

**Additional context**
I don't refer to the 'Randomize Runes' feature. That scrambles the characters each time, even if I write A B C twice. I'm talking about that feature being turned off and the characters representing their actual character.

**Comment by mclemente** [comment]
This is doable, but most fonts on Polyglot only suport 36 characters (0-9 a-z), so accents (e.g. `é ç`) and symbols like `-` won't show up on the text.
