### ISSUE TITLE
Trying to update gives error about manifest file

### ISSUE THREAD

**Issue by kuchrk24** [League-of-Foundry-Developers/fvtt-module-polyglot#184]
**Describe the bug**
Trying to update gives error about manifest file

**To Reproduce**
1. Update to or try to install v1.7.10 and foundry returns error about invalid manifest file
![image](https://user-images.githubusercontent.com/74018852/129283859-5c33f87c-eaa2-43a2-8088-6025603bf898.png)

**Comment by kuchrk24** [comment]
Looks like a comma missing on line 14 of modules.json

**Comment by mclemente** [comment]
Yup, just noticed it 🤦. Should be fixed now.
