### ISSUE TITLE
Não detecta as linguagens da ficha no T20!

### ISSUE THREAD

**Issue by TheLohan** [League-of-Foundry-Developers/fvtt-module-polyglot#190]
Description
The module it isn´t detecting the languages of charcters sheet.

**To Reproduce**
When I click on the token the language does not appear to select in chat and an error appears on concole.

 - Tormenta20 1.3.0.7
 - Polyglot 1.7.17
 -Babele - No

![image](https://user-images.githubusercontent.com/51961163/132999856-103be9ca-758b-4279-8cdd-b722fc873a12.png)

**Comment by mclemente** [comment]
Consertei.
