### ISSUE TITLE
Automatic (Random) or manual population of unspecified NPC languages

### ISSUE THREAD

**Issue by Juanfrank** [League-of-Foundry-Developers/fvtt-module-polyglot#191]
**Is your feature request related to a problem? Please describe.**
Not related to a problem.
Since the Polyglot module addresses language differences in different VTT systems, I was thinking of a feature that provides the module with the functionality of populating the NPC languages, when the actor has one of the following fields as a language:
1. the languages it knew in life / all languages it spoke in life / understands the languages of its creator but can't speak.
2. any one language, any two languages, etc. / May include the (usually X).
3. Common (this could be any language) plus one more / plus one of your choice.
4. Etc.

**Describe the solution you'd like**
Two options:

1. Automatic: including an optional feature for the Module where actors/tokens upon [creation/language field filling/token placement] the GM gets the option of randomly populating the languages section of the actor/token according to (probably) a regex matching of the languages "custom" field of the actor, including the same regex for the amount.
2. Manual: Same as above, but the GM would get the option of choosing the languages limited by the amount described by a regex expression with the amount provided in the actor's language custom field.

**Describe alternatives you've considered**
It could also be a global macro that runs the check on every actor in your World, which then starts the populating process by either of the methods described above.

**Additional context**
This would circumvent the annoying scenario where your NPC's or creatures have their custom field has one of the examples provided above, and the Module interprets it as being a language of its own.

Since this is very specific, the regex could potentially be very vague to account for any system. Since this would be a regex based feature, it would potentially have to be i18n'd in the lang files.

**Comment by mclemente** [comment]
Closing this issue as this feature was added in 1 Nov 2021 (https://github.com/League-of-Foundry-Developers/fvtt-module-polyglot/commit/cbebcc97c96c787b75de57b54cc01f4d6374db02).
