### ISSUE TITLE
[V9] Null settings 

### ISSUE THREAD

**Issue by DarKDinDoN** [League-of-Foundry-Developers/fvtt-module-polyglot#208]
**Describe the bug**
Hello,

Since V9, empty settings now appears to be `null`.
![image](https://user-images.githubusercontent.com/1687854/148086563-b1e124b5-d173-4eb3-b0d3-2fd24631f959.png)

Well `null` there is an error on init:
![image](https://user-images.githubusercontent.com/1687854/148086657-5b1faaa2-a3d7-4b8f-9081-b15b52a47359.png)

 - Are you using Babele? Yes

**Comment by mclemente** [comment]
I couldn't replicate it. A new world has that line empty.

**Comment by DarKDinDoN** [comment]
@mclemente So it appears to be a migration issue 0.8 -> 9
Foundry wide!

Apologies for the inconvenience.
Added some temporary dummy text before emptying again, and it now works as expected.
