### ISSUE TITLE
Add Splittermond support, for detection of language items

### ISSUE THREAD

**Issue by gsterling** [League-of-Foundry-Developers/fvtt-module-polyglot#209]
**System Name:**
Splittermond

**System Repository or Foundry VTT address:**
https://bitbucket.org/rpgframework-cloud/splittermond-fvtt/

**Does the system has the languages set up on Foundry?**
There are hundreds of languages, which aren't hard-coded in the system. They are free text items. It wouldn't be viable to list them all.

**Does the system uses languages as items?**
Yes. The item type is: "language".

**Additional context**
The system currently only supports german. I just want to be able to use the items as is, without naming all of them "Language (<foobar>)". I am fine with adding the ones I need most into the settings, like the generic approach, but it bugs me, that I would have to rename all items. It would be nice if it would just look for that specifig item type in the character sheet instead of all items and filter by name. It wouldn't even be a problem, that the language names itself are in german, french or anything.

**Comment by mclemente** [comment]
Hey, it should work now. Sorry for the delay.

**Comment by mclemente** [comment]
It seems I got the release wrong and it didn't make it into this version, I'm sorry. It should be working on the next version: 1.7.31.

**Comment by gsterling** [comment]
It is working though. Just the numbering is off, and it always installs over itself when updating.
