### ISSUE TITLE
Literacy and illiteracy for characters

### ISSUE THREAD

**Issue by gsterling** [League-of-Foundry-Developers/fvtt-module-polyglot#213]
**Is your feature request related to a problem? Please describe.**
We play a setting where literacy is a skill you need to aquire. So players without literacy should not be able to read any text in any language in a journal.

**Describe the solution you'd like**
Define an item making the player literate. Maybe the same as the default language item type or even better have it configurable which item defines the literate status, if it's a different type of item instead of language.

**Describe alternatives you've considered**
Making journals only accessible for players with literacy, but it's quite the hassle to setup each journal entry seperately for each player and they can't see the journal on the map. I would like to let them know automatically there IS something, but they can't read it.

**Additional context**
I already found you talking about something similar here: https://github.com/League-of-Foundry-Developers/fvtt-module-polyglot/issues/103#issuecomment-817395830

But as far as I can see, this did not get implemented. I don't even need the different levels of reading comprehension. Just a simple "can" or "can't".

**Comment by mclemente** [comment]
Is that for DSA5 as well?

**Comment by gsterling** [comment]
No, for "Splittermond", but I don't see why it should be for just this system. I would even be happy if you'd just add the option for an "illiterate" language, that does prevent players from reading journals in clear text. This way it would be better suited for a lot of systems.

It would be kinda work-around-ish for me, but doable and way easier for you, if my original request is not easily implemented, if my setting is the only one using a literate skill instead of illiterate.

**Comment by mclemente** [comment]
>but I don't see why it should be for just this system

Polyglot supports 23 systems, only 4 have literacy, there's no point in adding it to other systems. It's a lot of work for a feature that might not be used since it isn't in a system's rules.

>if my original request is not easily implemented, if my setting is the only one using a literate skill instead of illiterate.

It's easy, my main issue is figuring out what is `Literate`, since the game is in German. Is that item's type `language` as well?

**Comment by gsterling** [comment]
> > but I don't see why it should be for just this system
> 
> Polyglot supports 23 systems, only 4 have literacy, there's no point in adding it to other systems. It's a lot of work for a feature that might not be used since it isn't in a system's rules.

If it's not a problem doing it for just splittermond, that would be nice :)

I was under the impression, that most systems might not have a literacy skill, but rather characters 'flaws' like ugly, one-eyed or or just illiterate. But if you want to create it specifically for the splittermond system, that's really nice of you.

> 
> > if my original request is not easily implemented, if my setting is the only one using a literate skill instead of illiterate.
> 
> It's easy, my main issue is figuring out what is `Literate`, since the game is in German. Is that item's type `language` as well?

The item-type of it is "strength" and the strength is called "Literat". There is not official english translation as of now, but I doubt the system is even known outside of german speaking countries.

You could add it as an additional language item as well. While this wouldn't bother me, it's not working out of the box for others, that do not know about it. If they don't manage to add the "Literat" strength to their characters as intended by the system and want to use polyglot, they can't be helped imho. :smile:

**Comment by mclemente** [comment]
Ok, being Literate allows you to read the languages you know, no need for a Literate item for each language you know, right?

**Comment by gsterling** [comment]
> Ok, being Literate allows you to read the languages you know, no need for a Literate item for each language you know, right?

Correct. And just to be sure, it's "Literat" without an "e".

**Comment by gsterling** [comment]
You are awesome!
