### ISSUE TITLE
New language is not correctly detected everywhere in Splittermond

### ISSUE THREAD

**Issue by gsterling** [League-of-Foundry-Developers/fvtt-module-polyglot#215]
**Describe the bug**
When I added a new language (hightlighted) in Splittermond:
![image](https://user-images.githubusercontent.com/58980630/152636545-3a1320b5-3226-4b1c-8cc4-b14b4fecf0ff.png)
It was showing up in the chat window.
![image](https://user-images.githubusercontent.com/58980630/152636592-d22c6441-1e2f-4552-8ca1-e1a69870e477.png)
But it did nothing. Even the green globe is missing from the card. As compared to another language or the default language. In this order:
![image](https://user-images.githubusercontent.com/58980630/152636603-927f4075-b52b-4a12-a57c-b0b3faad2d9f.png)
It does show up in journals and does work with a language item on a charater sheet for a player.

When writing in a journal it does not translate the text, as it should. Admin view with scrambled texts:
![image](https://user-images.githubusercontent.com/58980630/152637864-359cb720-0af3-4f3e-9d31-1573297c9301.png)

It does work though, if the character has the desired language:
![image](https://user-images.githubusercontent.com/58980630/152637846-ac15b5b8-6588-4838-bf9e-09c64ee605bc.png)

If the character does not have the desired language, it breaks. First is the default language, second is known, third ist the new one (unknown) and the last one is unknown, too. The last two lines should be unreadable. It breaks when encountering the new language and the character does not know it. After that all text is clear.
![image](https://user-images.githubusercontent.com/58980630/152637801-31f4acb5-0804-49e9-921b-94ef93cf516e.png)

It also doesn't show up on the language settings window:
![image](https://user-images.githubusercontent.com/58980630/152636857-e3c1a33b-916d-434f-8da3-d8e93dffb081.png)

**To Reproduce**
1. Add languages: Basargnomisch,Patalisch,Zwingardisch,Furato,Dragoreisch
2. Add custom fonts to all of them
2. Add another language: Mertalisch
3. Do all of the above mentioned things

I am not sure which of these is important or if I missed anything. It just doesn't work. At all. And I don't see why.

**Expected behavior**
Have an theoretical unlimited quantity of languages all behave the same and use them in the same sentences in journals without breaking other languages.

**Versions**
 - Foundry Latest (9.249)
 - Browser: Firefox (96.0.3) and Chromium (98.0.4758.80)
 - System: Splittermond Latest (0.7.3)
 - Polyglot Latest (1.7.32)
 - Are you using Babele? -> No

**Additional context**
* I have created 6 languages in total. Is this a limit?
* I disabled all modules, except polyglot. Still not working.
* I reloaded all windows and even restarted the foundry service. The problem persists.
* I noticed this, when trying to create text with different languages mixed. Something that did work before, without the new language, and still does.

**Comment by mclemente** [comment]
I overengineered the support for Splittermond and forgot Custom Languages are how you get languages for systems that don't have languages setup already.
