### ISSUE TITLE
System support for GURPS 4e 

### ISSUE THREAD

**Issue by Zefarch** [League-of-Foundry-Developers/fvtt-module-polyglot#218]
**System Name:**
GURPS 4th Ed. Game Aid (Unofficial) 

**System Repository or Foundry VTT address:**
https://foundryvtt.com/packages/gurps

**Does the system has the languages set up on Foundry?**
No

Languages in GURPS are interpreted as advantages and formatted like such as actor data:
![image](https://user-images.githubusercontent.com/99354518/153270839-b126c22d-49dd-47d3-9a48-a5e9b2dba8ba.png)
Languages can only be added as advantages. 

I see that GURPS is already a supported system, but have yet to find anyone who got the module working for GURPS.

**Comment by mclemente** [comment]
Change the name from `Language: Common` to `Language (Common)` and it'll show up.
