### ISSUE TITLE
storyteller

### ISSUE THREAD

**Issue by Benjaneer** [League-of-Foundry-Developers/fvtt-module-polyglot#220]
**Is your feature request related to a problem? Please describe.**
I would love if this also integrated with the storyteller add-on

**Describe the solution you'd like**

**Describe alternatives you've considered**
I tried adding the span attributes class, title, and data-language but that didn't seem to be enough.

**Additional context**

**Comment by mclemente** [comment]
Damn, that module ran past my radar. It was a simple hook, since the Story doesn't trigger the same hook as a Journal.

Please, be sure to close https://github.com/Xbozon/storyteller/issues/23 as well.

**Comment by Benjaneer** [comment]
it looks like in v10 this may have gotten disconnected again

**Comment by Benjaneer** [comment]
I take it back, I don't see polyglot in the journal page editor for anything (I disabled all other modules).
![image](https://user-images.githubusercontent.com/9536408/218294260-6133fc28-f862-45e1-964e-a0ef1b5e1526.png)
![image](https://user-images.githubusercontent.com/9536408/218294253-c64257d6-7e75-469c-b23f-1e966a69d9f8.png)

Foundry Virtual Tabletop: Version 10, 10.291
Game System: dnd5e, 2.1.4
Active Modules: 2
Performance Mode: 3

OS: Unknown
Client: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) FoundryVirtualTabletop/10.291.0 Chrome/104.0.5112.102 Electron/20.1.0 Safari/537.36
GPU: ANGLE (AMD, AMD Radeon RX 5500 XT (navi14 LLVM 15.0.7), OpenGL 4.6)
Max Texture Size: 16384

Scene: 3840 x 1920 | Grid Size: 100 | Padding Percentage: 0
Walls: 0 | Ambient Lights: 5 | Ambient Sounds: 0 | Tiles: 1 | Tokens: 0

Actors: 0 | Items: 0 | Journal: 1 | Rollable Tables: 0 |
Playlists: 0 | Compendium Packs: 13 | Chat Messages: 2

**Comment by mclemente** [comment]
Polyglot doesn't work on ProseMirror editor #268, try using TinyMCE instead.

**Comment by Benjaneer** [comment]
I'm still not seeing it (if the default editor doesn't work then shouldn't TinyMCE be a dependency? though that doesn't seem to be working either)
![image](https://user-images.githubusercontent.com/9536408/218644284-74f5d2d1-9831-4984-b31b-05e4a7c6d98d.png)

**Comment by Benjaneer** [comment]
AH! there is a "TinyMCE" module, which apparently interferes with the TinyMCE baked in :$
disabled that junk and now it's working :)
Thanks
