### ISSUE TITLE
Players unable to type in languages on character sheet [solved]

### ISSUE THREAD

**Issue by SkuzzillButt** [League-of-Foundry-Developers/fvtt-module-polyglot#221]
**Describe the bug**
Players are unable to select a language they know on the character sheet and type with that language in OOC or In Character. However I as the GM am able to type in whatever language I want.

**Expected behavior**
Characters with a language selected on the character sheet should be able to choose it in the chat window.

**Screenshots**
GM View

![FoundryVTT_jxLPEP4RqI](https://user-images.githubusercontent.com/100530181/155892322-1f58a358-8a71-44d5-b13a-148de5c4c033.png)

Player View

![chrome_vU8ZCEbgtP](https://user-images.githubusercontent.com/100530181/155892343-4796d01b-b260-4b94-809f-a81948efeef2.png)

 - dnd5e 1.5.7
 - Polyglot Version 1.7.37
 - Are you using Babele? [No]

**Comment by mclemente** [comment]
Have the players selected the character? If not, are the characters on the map?
![image](https://user-images.githubusercontent.com/5288872/155894706-e6b5d120-4ca4-475b-a476-bf9c7d9ec62f.png)

**Comment by SkuzzillButt** [comment]
Went to test again, it looks like the characters needed to be selected. This must've been because they had just created the actors that session and hadn't re-logged to force Foundry to have them select the character. Thank you.
