### ISSUE TITLE
Always default to default language?

### ISSUE THREAD

**Issue by chadberg** [League-of-Foundry-Developers/fvtt-module-polyglot#23]
I was hopeful with the new ability to pick a default language.... but that setting doesn't seem to actually do much. Even when set to 'Common', or left blank to be system default, when my character logs in the language is set to the first language he speaks, alphabetically. In this specific case that means logging in the chat window is set to Celestial before Common.

Further, it might be helpful to have the option to have the language revert back to the configured default language after every message is sent, and to only use a non-default language when explicitly chosen for that message. This would avoid the frequent problem we have in the game of players having to type things twice because they forgot to reset their language choice. This is especially problematic at the start of game when players are logged in with the wrong default language (and has unfortunately given the table a poor impression of the software).

**Comment by diannetea** [comment]
This is no longer working as of foundry 0.7.6, I have the default set to Common but after every refresh my language is set to Abyssal.
