### ISSUE TITLE
Custom System Builder Support?

### ISSUE THREAD

**Issue by SophieScott12** [League-of-Foundry-Developers/fvtt-module-polyglot#237]
Is there a way to allow Polyglot to work with the Custom System Builder system without Items?  I can create items and drag them to the character sheets and it'll work just fine, but CSB doesn't have any way to actually see or manipulate items attached to a sheet (yet?), so doing so would not be ideal.  If there is no way currently, perhaps that could be added?  I don't know how complicated that would be.

**Comment by mclemente** [comment]
I finally found a solution as long as the languages are set as a plain string of text separated by comma or semicolon. It should be out on version 1.8.3 of the module.
