### ISSUE TITLE
Rework of the Module

### ISSUE THREAD

**Issue by elizeuangelo** [League-of-Foundry-Developers/fvtt-module-polyglot#238]
Instead of having a set of behaviors: one for messages created and one for journals, everything could be much more simplified if we simply had a span class wich encompassed all the behavior we want. Like a ```<span class="polyglot" data-language="LANGUAGE" data-seed="SEED">ENCODED_TEXT</span>``` (need to show encoded_text in case the module is disabled to load or fails for any reason).

The module would identify those special spans anywhere inside Foundry and appropriately convert them to the correct font. You could even use different languages inside same text if you are familiar with HTML.

That class could even be used anywhere the GM wanted, even copied and pasted in HTML form.

**Comment by mclemente** [comment]
I'll try doing this once V10 is stable. I'm trying to update it to V10.270 and there's some issues with the current implementation of the new Journal and some new ones might arise before it's eventually out.

**Comment by elizeuangelo** [comment]
I tried implementing POLYGLOT tags wich converted to appropriate span tags but it turned out not helping simplifying the module, we want CHAT and JOURNAL behavior to be different otherwise lots of funcionalities are removed. I tried setting different 'styles' to the POLYGLOT tag but it defeats the purpose.
