### ISSUE TITLE
With dnd 1.6, adding custom languages always replaces

### ISSUE THREAD

**Issue by mmacgibbon** [League-of-Foundry-Developers/fvtt-module-polyglot#241]
**Describe the bug**
If you have dnd 1.6 installed, and you have any custom languages in polyglot, it replaces the system languages even if you dont have the checkbox to replace them selected.

![image](https://user-images.githubusercontent.com/2736379/177011160-e1c4d7f3-960f-497a-b7b4-8a8ff3edfb2c.png)

**To Reproduce**
1. Add "Test" to Custom Languages '...'
2. Look at users languages, see the default languages are no longer an option

**Expected behavior**
unless you choose to replace the languages it should ADD to the language list, not replace them.

**Screenshots**
![image](https://user-images.githubusercontent.com/2736379/177011220-38318fb7-3a61-408e-bd9d-fc0e6ac4a731.png)

 - Game System and version dnd5e 1.6.3
 - Polyglot Version:  1.7.40
 - Are you using Babele? No

**Additional context**

**Comment by mclemente** [comment]
I couldn't replicate this on a brand-new world. Could you try it on a new world just to be sure?

Also, zip your world folder and send it to me so I can take a look what's going on.

**Comment by mmacgibbon** [comment]
ill try it on a brand new world.  can you take a .tgz (tar.gzipped)?  i run mine on linux.

**Comment by mclemente** [comment]
Sure, I can.

**Comment by mmacgibbon** [comment]
Interesting you're right.  on a vanilla world, its not a problem.
