### ISSUE TITLE
FGG : Custom languages do not push on character sheet

### ISSUE THREAD

**Issue by jello195** [League-of-Foundry-Developers/fvtt-module-polyglot#243]
**Describe the bug**
In the FGG system, when you add custom languages they are pushed everywhere in the game but they are not on the character's sheet. Which in therm makes it impossible for a PC to know a custom language.

**To Reproduce**
1. Add custom languages
2. Open a character sheet (PC not NPC)
3. Try to add language
4. Notice the native languages are still present but not the custom ones

**Expected behavior**
the list should contain native and custom languages (or only custom if the option was selected)

**Screenshots**
![image](https://user-images.githubusercontent.com/83799020/180591282-390614d0-18d8-42d6-9f7b-6209fd5f48bb.png)
![image](https://user-images.githubusercontent.com/83799020/180591494-711eb468-29d1-46d9-b13f-2b216861393e.png)

 - FGG
 - Polyglot 1.7.4

**Comment by mclemente** [comment]
The latest version has fixed this issue. Thank you for reporting it.
