### ISSUE TITLE
preview wipes font style

### ISSUE THREAD

**Issue by Benjaneer** [League-of-Foundry-Developers/fvtt-module-polyglot#252]
**Describe the bug**
when I toggle runes the font style (like font and size) are removed
though, when a player opens it they do see what I want them to, this just makes character blocking a little more difficult to plan how it will line up for their viewing.

**To Reproduce**
1. add some polyglot'ed text and change the font and/or font-size
2. click the "Toggle Runes" button

**Comment by mclemente** [comment]
Next update will introduce a setting that will let you disable the font's size from journals.

**Comment by Benjaneer** [comment]
looks like this bug is still present (or reintroduced?)

**Comment by mclemente** [comment]
I'm not having this issue.

**Comment by Benjaneer** [comment]
do you run it as the app or in the browser?
(not that it's critical anyhow)
![image](https://user-images.githubusercontent.com/9536408/218645825-f71e5e65-89d3-4235-8b54-6d04e0e8e6e4.png)
![image](https://user-images.githubusercontent.com/9536408/218645850-5d40dfb3-ae96-4b4b-858b-61db7bd362b8.png)
![image](https://user-images.githubusercontent.com/9536408/218645878-b2f81564-1e1a-47ba-9636-ad9fa08e4363.png)

**Comment by mclemente** [comment]
I see now. I can fix this, but there is one limitation: you can't use two fonts for the same scrambled text. Looking at your text, that shouldn't be a problem.
