### ISSUE TITLE
Polyglot Fonts Added to Core and Other Modules by Default

### ISSUE THREAD

**Issue by Armandeus66** [League-of-Foundry-Developers/fvtt-module-polyglot#253]
Polyglot seems to add its fonts to core and other modules without setting it to do so.

Default Language is left blank.
Add Fonts to Module Settings is None.
Add Polyglot's Fonts to Core is not checked.

Using Foundry v10.285, the rune/fantasy fonts that Polyglot uses appear in the journal font list, and in modules like Dice So Nice.

 - Game System: Pathfinder 2E v4.0.3
 - Polyglot Version 1.8.1
 - Are you using Babele? No

**Comment by mclemente** [comment]
It's supposed to remove the fonts when you toggle `Add Polyglot's Fonts to Core` off, try toggling it on and off to remove them altogether. That said, I can see why you wouldn't want this on by default and will change it to be off by default.

**Comment by Armandeus66** [comment]
This has been closed, but is not fixed. 
I still see Polyglot fonts in the journal and Dice So Nice, with "Add Polygot's Fonts to Core" unchecked.
I tried checking it, saving, unchecking, saving, and looking again, but the fonts were still in the journal and DSN.

Foundry 10.285
System PF2E 4.0.6
Polyglot 1.8.3
Babele no (what is this?)
