### ISSUE TITLE
Using Polyglot in Journal Entries Impossible

### ISSUE THREAD

**Issue by KnoepfchenFulla** [League-of-Foundry-Developers/fvtt-module-polyglot#262]
I am unable to use Polyglot in Journal Entries since updating to V10. 

In the default sheet configuration, Polyglot no longer appears in the drop down menu at all:

![2022-10-01_12-31-23](https://user-images.githubusercontent.com/79639045/193405497-48c9d020-21f1-4c2e-802f-a9445a0319ca.jpg)

When I change the sheet to TinyMCE, Polyglot appears, but is greyed out:

![2022-10-01_12-31-51](https://user-images.githubusercontent.com/79639045/193405515-e994b76d-0208-45c5-b59e-ff8529029abc.jpg)

**Game System and version**
 - Polyglot Version: current
 - Are you using Babele? no
 - Foundry Version: 10 (current)
 - System: The Dark Eye (system and modules all up to date)

**Comment by mclemente** [comment]
I can't reproduce this on a brand new world. Can you send me your world's settings.db? It should be on `your world's folder/data` folder.

**Comment by KnoepfchenFulla** [comment]
I use The Forge, here's the settings.db from the world export (zipped to be able to attach it here).
[settings.zip](https://github.com/League-of-Foundry-Developers/fvtt-module-polyglot/files/9691976/settings.zip)

**Comment by mclemente** [comment]
Hm, it still works for me. Are there any errors on the Console (F12) when opening the editor?

**Comment by KnoepfchenFulla** [comment]
I deactivated and reactivated Polyglot, these are the errors that I get in the Console:

![2022-10-02_21-33-45](https://user-images.githubusercontent.com/79639045/193472825-07b250be-6916-4a3c-b8bc-bcc69da127a3.jpg)

**Comment by mclemente** [comment]
Activate the DSA5 Core Rules module. Any other errors?

**Comment by KnoepfchenFulla** [comment]
Hm, that's strange, the DSA5 Core Rules module was active when I took the screenshot yesterday. 
I just updated Polyglot, and the problem's still there, with just one change in the first row:

LanguageProvider.js:1218 Uncaught (in promise) TypeError: Cannot read 

It does not seem to be the core module itself, but the core special abilities?

```
		if (game.modules.has("dsa5-core") && game.modules.get("dsa5-core")?.active) {
			const dsa5Pack = game.packs.get("dsa5-core.corespecialabilites");
			const dsa5ItemList = await dsa5Pack.getIndex();
```
I also tried switching the language of my world from German to English to see if there might be an issue there (as "special abilities" are "sonderfertigkeiten" in German and the system has been known to get confused with such terminology differences between languages), but the issue with Polyglot is still the same in English as well.

**Comment by KnoepfchenFulla** [comment]
Hey, I installed the latest update just now (where you changed the line), but the error still presents the same:

![2022-10-03_12-44-01](https://user-images.githubusercontent.com/79639045/193558993-522b34f0-cddb-43ee-a0e0-b32860c72276.jpg)

**Comment by mclemente** [comment]
If you enter `game.packs.get("dsa5-core.coreabilities")` in the console, does it return anything other than undefined?
The id for the compendium with languages was changed from V9 to V10. I don't own the Core Rules, so I can't test stuff for DSA5.

**Comment by mclemente** [comment]
Just spoke with Huepfklotz, there was a typo on that compendium's id. Be sure to update it and the error should be gone.
