### ISSUE TITLE
17 warning about fonts!

### ISSUE THREAD

**Issue by dharkus5000** [League-of-Foundry-Developers/fvtt-module-polyglot#264]
**Describe the bug**
I get 17 warnings about polyglot - listed below - i've put an extra line or 2 inbetween where the warnings change by more than just the font names, and i've listed them in the order foundry gives them to me
`downloadable font: maxp: Bad maxZones: 0 (font-family: "Thorass" style:normal weight:400 stretch:100 src index:0) source: https://assets.forge-vtt.com/bazaar/modules/polyglot/1.8.4.4/fonts/Thorass.otf`
`downloadable font: maxp: Bad maxZones: 0 (font-family: "Barazhad" style:normal weight:400 stretch:100 src index:0) source: https://assets.forge-vtt.com/bazaar/modules/polyglot/1.8.4.4/fonts/Barazhad.otf`
`downloadable font: maxp: Bad maxZones: 0 (font-family: "OldeThorass" style:normal weight:400 stretch:100 src index:0) source: https://assets.forge-vtt.com/bazaar/modules/polyglot/1.8.4.4/fonts/OldeThorass.otf`
`downloadable font: maxp: Bad maxZones: 0 (font-family: "Semphari" style:normal weight:400 stretch:100 src index:0) source: https://assets.forge-vtt.com/bazaar/modules/polyglot/1.8.4.4/fonts/Semphari.otf`
`downloadable font: maxp: Bad maxZones: 0 (font-family: "Celestial" style:normal weight:400 stretch:100 src index:0) source: https://assets.forge-vtt.com/bazaar/modules/polyglot/1.8.4.4/fonts/Celestial.ttf`
`downloadable font: maxp: Bad maxZones: 0 (font-family: "Iokharic" style:normal weight:400 stretch:100 src index:0) source: https://assets.forge-vtt.com/bazaar/modules/polyglot/1.8.4.4/fonts/Iokharic.otf`
`downloadable font: maxp: Bad maxZones: 0 (font-family: "Dethek" style:normal weight:400 stretch:100 src index:0) source: https://assets.forge-vtt.com/bazaar/modules/polyglot/1.8.4.4/fonts/Dethek.otf`
`downloadable font: maxp: Bad maxZones: 0 (font-family: "HighDrowic" style:normal weight:400 stretch:100 src index:0) source: https://assets.forge-vtt.com/bazaar/modules/polyglot/1.8.4.4/fonts/HighDrowic.otf`
`downloadable font: maxp: Bad maxZones: 0 (font-family: "HighDrowic" style:normal weight:400 stretch:100 src index:0) source: https://assets.forge-vtt.com/bazaar/modules/polyglot/1.8.4.4/fonts/HighDrowic.otf`
`downloadable font: maxp: Bad maxZones: 0 (font-family: "Espruar" style:normal weight:400 stretch:100 src index:0) source: https://assets.forge-vtt.com/bazaar/modules/polyglot/1.8.4.4/fonts/Espruar.otf`
`downloadable font: maxp: Bad maxZones: 0 (font-family: "Espruar" style:normal weight:400 stretch:100 src index:0) source: https://assets.forge-vtt.com/bazaar/modules/polyglot/1.8.4.4/fonts/Espruar.otf`

`downloadable font: OS/2: Bad usWidthClass: 0, changing it to 1 (font-family: "Tuzluca" style:normal weight:400 stretch:100 src index:0) source: https://assets.forge-vtt.com/bazaar/modules/polyglot/1.8.4.4/fonts/Tuzluca.ttf`

`downloadable font: maxp: Bad maxZones: 0 (font-family: "Qijomi" style:normal weight:400 stretch:100 src index:0) source: https://assets.forge-vtt.com/bazaar/modules/polyglot/1.8.4.4/fonts/Qijomi.otf`
`downloadable font: maxp: Bad maxZones: 0 (font-family: "Reanaarian" style:normal weight:400 stretch:100 src index:0) source: https://assets.forge-vtt.com/bazaar/modules/polyglot/1.8.4.4/fonts/Reanaarian.otf`
`downloadable font: maxp: Bad maxZones: 0 (font-family: "Ophidian" style:normal weight:400 stretch:100 src index:0) source: https://assets.forge-vtt.com/bazaar/modules/polyglot/1.8.4.4/fonts/Ophidian.otf`
`downloadable font: maxp: Bad maxZones: 0 (font-family: "OldeEspruar" style:normal weight:400 stretch:100 src index:0) source: https://assets.forge-vtt.com/bazaar/modules/polyglot/1.8.4.4/fonts/OldeEspruar.otf`
`downloadable font: maxp: Bad maxZones: 0 (font-family: "MarasEye" style:normal weight:400 stretch:100 src index:0) source: https://assets.forge-vtt.com/bazaar/modules/polyglot/1.8.4.4/fonts/MarasEye.otf`

**To Reproduce**
login to world

 - Game System and version PF2e 4.2.1
 - Polyglot Version 1.8.4.4
 - Are you using Babele? no

**Comment by mclemente** [comment]
Looks like #64 has made a comeback. It is pretty much harmless, but it shall be fixed on the next release.
