### ISSUE TITLE
Comprehend Languages - Feature Request

### ISSUE THREAD

**Issue by LyricalStreetPoet** [League-of-Foundry-Developers/fvtt-module-polyglot#34]
Is there an option to support the comprehend languages or tongues spell?  

Maybe make it where that spell creates a status effect on a token and then anybody with that effect can unscramble any spoken text or journal entry.  

For an easier implementation, could just let the GM temporarily unscramble the text by selecting the token of the player that cast the spell and then click the globe to unscramble it for that token.

**Comment by kakaroto** [comment]
Implementing something like that would be relatively complicated to be honest and I think it would make more sense to simply temporarily add the language to the player's actor for the duration of the spell.

**Comment by JamzTheMan** [comment]
Could you add a special language called "All" or "Any" and when you check if the character has the language also check for this special language "All" and unscramble if they have it?

Then instead of temporarily adding possibly multiple languages we could temporarily just add this one language?

Oh, this would work perfect for creatures with Truespeech and such as well?

**Comment by Juanfrank** [comment]
TBH you could just add the "All" as an option in the languages field and all characters who have this particular language would be able to understand it. You as a GM could just make an active effect for the Comprehend Languages spell or a similar feature, which grants that specific language.

It could even be hidden from the languages toggle window, just something off-the-record kind of stuff.

**Comment by Juanfrank** [comment]
Something I've noticed is DAE already includes a ``data.traits.languages.all`` which adds all languages availables in the dnd5e system config.

However I'll post a PR just in case other systems require a similar functionality. It's pretty straight-forward tbh.

**Comment by mclemente** [comment]
Done.
