### ISSUE TITLE
Can't set a custom language + anyone has ONLY a custom language can understand all the languages

### ISSUE THREAD

**Issue by p4535992** [League-of-Foundry-Developers/fvtt-module-polyglot#35]
**Environment Details**

Foundry VTT Version: 0.7.1

Operating System: [Linux]

How Are You Using Foundry: [Linux,Native Application (Electron), Chrome]

Which Game System: Dungeons and Dragons 5th Edition, version 0.95

Modules Enabled?: Yes

Module Version: 1.1.1

**Description of the issue:**

For help you with the tests here the token npc with a custom language i'm tring to use:

[fvtt-Actor-Wight.json](https://gitlab.com/p4535992/foundryvtt-modules-dev/-/blob/master/json-actors/fvtt-Actor-Wight.json)

_(1) Can't set a custom language on a player for make understand that custom language to other_

I'm want to set between two token 1 npc and 1 player (but it's mean nothing) a custom language.

1) The npc already have a custom language "test"
2) i set a custom language called "test" on the player
3) With the npc i write something on the chat log,
4) Go to the player token where i set a custom language with the same name "test" but can't understand what the npc have said.

![img1](https://i.imgur.com/0u92gHj.png)

_(2) A player with ONLY a custom language can understand all the other languages (Orchis,Elvish,ecc.)_

1) The npc spoke with the orchish or elvish language.
2) set a custom language "test" and the Orchis language on the player, all ok
3) remove the Orchish language and set only the custom language "test" on the player, now i can "understand" all the other languages.

![img1](https://i.imgur.com/vwikGHl.png)

let me know if you need other informations.

**Comment by elizeuangelo** [comment]
I believe this has already been addressed in PR #38 , please text it after the next release

**Comment by Naroek56** [comment]
I have a similar issue. Version: 1.4.0
I'm working with the Old School Essentials system. Deepcommon is missing as language in the list, so I tried to add it myself. As GM I can select it in chat, but I cannot add the language to the character sheet.
