### ISSUE TITLE
Language Macro

### ISSUE THREAD

**Issue by Smoldar-og** [League-of-Foundry-Developers/fvtt-module-polyglot#37]
I have some lore drops and hints on walls, that I use triggers to show on Journal what is written to players and would be nice to be able to show with a chat macro, with the user reading on the language instead; If already possible, would like to know what command to use.

**Comment by elizeuangelo** [comment]
Both issues #23  and #37  could be addressed together if we had a /speak command in chat.

`/speak [language] [message]` could be used for one-time messages, without the need to click on the choice menu.

**Comment by mclemente** [comment]
@Smoldar-og hello, this is in the works right now. In the future, it'll work just like elizeuangelo's message, `/speak [language] [message]`.

**Comment by mclemente** [comment]
@Smoldar-og On the next update (1.5.4), you will be able to input the following Script Macro `ChatMessage.create({content: "MESSAGE", speaker: ChatMessage.getSpeaker(), flags: {"polyglot": {"language" : "LANGUAGE"}}});`.
