### ISSUE TITLE
Savage Worlds

### ISSUE THREAD

**Issue by Freewolf2000** [League-of-Foundry-Developers/fvtt-module-polyglot#53]
Is there any way you can add support for Savage worlds for this Module? I would love to have this for Savage Worlds.

**Comment by kakaroto** [comment]
The same answer I gave before for starfinder would apply here : https://github.com/kakaroto/fvtt-module-polyglot/issues/20#issuecomment-655981446

**Comment by mclemente** [comment]
Unfortunately, Savage Worlds has no languages set up on its files.
Someone needs to add language support on SWADE before Polyglot can support it.
