### ISSUE TITLE
Disable highlight

### ISSUE THREAD

**Issue by Pawper** [League-of-Foundry-Developers/fvtt-module-polyglot#58]
Hello, I would like the option to disable the yellow highlighting. Thanks!
![image](https://user-images.githubusercontent.com/22269691/99849176-f0e61580-2b2f-11eb-86d8-90969c672b59.png)

**Comment by mclemente** [comment]
Hello, I just adopted this module, so I'm not used to the code exactly to add an option to change the CSS.
On the other hand, I've reduced the highlight's strength by 66%, so it isn't a solution for you, but might be a little better. You can also go to the `css/polyglot.css` file and replace `0.25` with `0`.
