### ISSUE TITLE
Polyglot option disappeared in native app

### ISSUE THREAD

**Issue by EikePeace** [League-of-Foundry-Developers/fvtt-module-polyglot#59]
Since the update, I have no way of using the Module when I'm navigatig in the native app.
It works great in my browser, but not at all in the application itself.

**Comment by kakaroto** [comment]
Nothing should affect it in that way. Can you press F12 and see if there's any error message in the console ?

**Comment by EikePeace** [comment]
Yeah

I deactivated all other modules as well to check if they had anything to do with it. It still happened


The Error:
foundry.js:1129 Uncaught (in promise) Error: The values of the provided object must be unique in order to invert it.
    at invertObject (foundry.js:1129)
    at Function.get defaultLanguage [as defaultLanguage] (polyglot.js:49)
    at PolyGlot.updateUserLanguages (polyglot.js:175)
    at PolyGlot.setCustomLanguages (polyglot.js:377)
    at async PolyGlot.renderChatLog (polyglot.js:58)

**Comment by EikePeace** [comment]
Okay, I did some Testing

It apparently happens, because of the ' in Thieves' Cant
