### ISSUE TITLE
Chat Bubbles aren't always translated

### ISSUE THREAD

**Issue by JohnSBarden** [League-of-Foundry-Developers/fvtt-module-polyglot#61]
I have a macro to replicate the module NPC Chatter, but with the added functionality of being able to choose a language from Polyglot.  So on a timer, a random message is pulled from a table and displayed in Undercommon.  Here's my code:

```
const chat = () => {
  // Roll for speech and choose a token
  const result = game.tables.getName("Xulgath Speech").roll().results[0].text;
  const activeScene = game.scenes.filter((x) => x.active)[0];
  const eligible = activeScene.data.tokens.filter((t) =>
    t.name.toLowerCase().includes("xulgath")
  );
  var speakToken = eligible[Math.floor(Math.random() * eligible.length + 0)];
  let speakActor = game.actors.entities.find((c) => c.name === speakToken.name);

  // Make the token speak
  $(`#polyglot select`).val("undercommon");
  console.log(speakToken, speakActor, activeScene, result);
  ChatMessage.create(
    {
      speaker: { token: speakToken, actor: speakActor, scene: activeScene },
      content: result,
      type: CONST.CHAT_MESSAGE_TYPES.IC,
      flags: {
        polyglot: {
          language: "undercommon",
        },
      },
    }
  );
  // chat bubble
  game.socket.emit("module.npc-chatter", {
    tokenId: speakToken._id,
    msg: result,
  });
  canvas.hud.bubbles.say(speakToken, result, false);
};

// Print one message immediately
chat();
// Timer
//NpcChatter.timer = window.setInterval(() => { chat(); }, 2000);
```

Every once in a while, independent of the message being printed and token speaking, the message is not translated in the chat bubble.  You can see in the screenshot below, all 3 messages print in the chat log correctly.

![image](https://user-images.githubusercontent.com/13333213/102565026-3ef42780-40a2-11eb-8793-ee11b2aa6212.png)

Here's the error thrown in the console in these cases 
![image](https://user-images.githubusercontent.com/13333213/102565503-351ef400-40a3-11eb-81d5-a1dc94134630.png)

Currently implementing both the flag and the selector mentioned in [this issue](https://github.com/kakaroto/fvtt-module-polyglot/issues/54).  If the selector isn't implemented, no chat bubbles are translated (in essence, the flag doesn't apply, since it's only on the chat message).

**Comment by mclemente** [comment]
Hello, can you try to replicate this issue on the new version? I've updated the system and need to make sure this issue still persists.
I might also make some changes so macros won't need the selector line anymore.
