### ISSUE TITLE
Add option to display translated text below original text

### ISSUE THREAD

**Issue by ironmonk88** [League-of-Foundry-Developers/fvtt-module-polyglot#63]
It's not always clear that the other person is speaking in a different language, if you don't catch the symbol in the upper right corner.

Would it be possible to add the option of displaying the original text untranslated with the translated text below it?

![Polyglot](https://user-images.githubusercontent.com/75920956/104761426-bb1c7200-5717-11eb-9e32-5f8061c9b0e6.png)

Thank you.

**Comment by ironmonk88** [comment]
Was that a "Just No" closing of the ticket?
I have the code working on my machine, makes life way easier than trying to catch a small icon changing colour.  Just never submitted a pull request 'cause I assumed the module was abandoned.

**Comment by mclemente** [comment]
Sorry, I just took over the module and was cleaning the issues. Could you make a Pull Request, then?

**Comment by ironmonk88** [comment]
Not a problem.  Should be added now.
And thank you for picking up the module!

**Comment by mclemente** [comment]
Thank you, merge accepted.

**Comment by ironmonk88** [comment]
Yayyyy.  Much appreciated.
Sorry about the Common/common issue, definitely one of those, it works well on my machine but I hadn't tested it on other systems.
Dunno if you got to it yet but changing line 223 to `if(lang.toLowerCase() != 'common' || unknown){` should help.

**Comment by mclemente** [comment]
No problem, I fixed it by changing the defaultLanguage() function to return `Common` instead of `common`.
