### ISSUE TITLE
Feature request: Being able to see the langage used

### ISSUE THREAD

**Issue by Darkiller25** [League-of-Foundry-Developers/fvtt-module-polyglot#66]
Hi!
Tanks for the awesome module, it helps a lot with immersion, but I have one caveat that I could not fix myself. When someone speaks in Elvish, for example, there is no way to see (even for the GM) what language it is. It would be nice to have an option to see something like "(Elvish) scrambled text"

Thanks!

**Comment by kakaroto** [comment]
There's a globe next to the chat message (red when the user can't read it, green when they can). You can hover on it to see what the language is.
I don't remember if there was an option to hide that from players, or if it's only GM, or if it's GM and players who can see the language in the globe's tooltip.

**Comment by Darkiller25** [comment]
So I was dumb after all :p thank you!
