### ISSUE TITLE
Polyglot Error when selecting tokens

### ISSUE THREAD

**Issue by JustinKovacich** [League-of-Foundry-Developers/fvtt-module-polyglot#70]
I don't know if this is an escape character thing but I get this whenever I click on one of my characters with Polyglot active and the polyglot language dropdown does not appear.

Error: The values of the provided object must be unique in order to invert it.
    at invertObject (foundry.js:1129)
    at Function.get defaultLanguage [as defaultLanguage] (polyglot.js:49)
    at PolyGlot.updateUserLanguages (polyglot.js:175)
    at PolyGlot.controlToken (polyglot.js:82)
    at Function._call (foundry.js:2496)
    at Function.callAll (foundry.js:2456)
    at Token.release (foundry.js:11661)
    at Token.release (overrides.ts:9)
    at TokenLayer.releaseAll (foundry.js:12285)
    at TokenLayer.releaseAll (foundry.js:40319)

Languages that appear in the character sheet as available:
![image](https://user-images.githubusercontent.com/32140377/107861780-0492d680-6e16-11eb-81b2-35fda4a8ec5e.png)

Custom Languages that are currently active in the settings (I have not removed the defaults):
Ovidic,B.A.S.I.C,Fae,Stoutkin,Elfkin,Fiendkin,Greenkin,Moan,Old Heartlandic,Arborkin,Ancient Clont,Thieves' Cant,Draconic,Druidic,Abyssal,Celestial,Wildtongue

Default:
Ovidic.

I had a lot of dashes and parenthesis before which I've dropped, so I don't know if that is affecting things?

This is happening on 0.7.9 / Polyglot 1.4.0.  

Any suggestions?

**Comment by mclemente** [comment]
I've made some changes to the module that might have unintentionally fixed this, because I can't replicate it.
Check if that character is still bugged on the latest version.

**Comment by JustinKovacich** [comment]
Hey!  Yes, I updated and its fixed.  Thanks for looking into it.  Love the Alexstraza icon, btw.

**Comment by mclemente** [comment]
Good to know. Thanks, haha.
