### ISSUE TITLE
Translated box for default language

### ISSUE THREAD

**Issue by JamzTheMan** [League-of-Foundry-Developers/fvtt-module-polyglot#73]
Is it meant to show a "translation" for the default/Common language? It adds a lot of space when "normal" talking is occurring, but I love the translated box otherwise!

![image](https://user-images.githubusercontent.com/8051654/107968333-da572b00-6f73-11eb-860e-0af24dcd1a1d.png)

**Comment by mclemente** [comment]
Not intended, it happens on any system that has Common as the default language, which wasn't the case for system I've tested this change on.
It'll be fixed on the next release.
