### ISSUE TITLE
Feature Request: Let me as a GM post message in chat as language

### ISSUE THREAD

**Issue by zLaddeus** [League-of-Foundry-Developers/fvtt-module-polyglot#78]
Hi!

I don't know if I'm doing something wrong here but, it looks like I can't just type something as a GM in chat, and have it be in the language I select. It can be done if I select a token first, but then that token needs to have that language.

Sometimes I just want to display something they hear or read, without having to have a token or journalpage ready.

Is this possible to do?

Cheers!

**Comment by mclemente** [comment]
You're able to do that already. What system are you on?

**Comment by zLaddeus** [comment]
> You're able to do that already. What system are you on?

We're running Pathfinder 2e.
I've tried with a number of languages.

This is how it looks for me:
![image](https://user-images.githubusercontent.com/71599968/109397840-28d3d480-7939-11eb-8fcd-66cdbb2ba532.png)

And if I log in as a player that doesn't know Gnomish (on the same computer, through internet-link, not the local) it looks like this:
![image](https://user-images.githubusercontent.com/71599968/109397848-3d17d180-7939-11eb-846d-172f015a5549.png)

But, if I as GM have a token selected and write something, it comes out correct:
![image](https://user-images.githubusercontent.com/71599968/109397880-751f1480-7939-11eb-8210-3ef178aa5903.png)

Even for the same player above:
![image](https://user-images.githubusercontent.com/71599968/109397884-836d3080-7939-11eb-8763-f1c14b7be62e.png)

So, for me it only works if I have something selected.
Which doesn't really work if I just want to post a paragraph of text.

These are my settings:
![image](https://user-images.githubusercontent.com/71599968/109397923-b7e0ec80-7939-11eb-8af8-73d24e2cfb8d.png)

Am I doing something wrong?

**Comment by mclemente** [comment]
Toggle `Scramble on OOC chat messages`.
