### ISSUE TITLE
Common language being scrambled

### ISSUE THREAD

**Issue by Tensaisenshi** [League-of-Foundry-Developers/fvtt-module-polyglot#81]
Hi

My chat messages in common language are being scrambled when using Brazilian Portuguese translation. By changing Foundry language to English it doesn't happen.
I tried to set the Default Language to common, Common, comum and Comum ( comum = common in portuguese) as well as leave it empty. Nothing changed.
I'm using D&D5e. Didn't testes other systems.

![image](https://user-images.githubusercontent.com/12926746/109263274-c1efd780-77e1-11eb-9abb-a28219131545.png)

**Comment by mclemente** [comment]
Vish, isso deve acontecer com todas as traduções do 5e. Fiz umas mudanças e agora deve funcionar normalmente.

**Comment by Tensaisenshi** [comment]
Eu aqui gastando meu inglês e voce fala português.
Agora está funcionando. Obrigado.
