### ISSUE TITLE
WRFP4 wrong name used for match

### ISSUE THREAD

**Issue by mcailleaux** [League-of-Foundry-Developers/fvtt-module-polyglot#82]
https://github.com/League-of-Foundry-Developers/fvtt-module-polyglot/blob/7bb8e2b699ea53a1405403da7230c78f0133dd7d/src/polyglot.js#L138

You use the wrong name on your bugfix for other language support, replace item.name by the name variable you have declared before

**Comment by mcailleaux** [comment]
The Pull Request by @sladecraven is the best way to manage module support language instead of my suggestion : https://github.com/League-of-Foundry-Developers/fvtt-module-polyglot/pull/83

**Comment by mclemente** [comment]
I've accepted that merge and released a new version. Thank you.
