### ISSUE TITLE
[WHFRP] correction of default language selection dont work because of case

### ISSUE THREAD

**Issue by mcailleaux** [League-of-Foundry-Developers/fvtt-module-polyglot#86]
Your correction for default langage case dont work, the problem is on line 204 where you compare the lowercase defaultLanguage with the Titlecase values of this.known_languages, it never match and the result is always [...this.known_languages][0]

![image](https://user-images.githubusercontent.com/18030833/109843993-fa613c80-7c4b-11eb-880f-c66547ccd591.png)

**Comment by mclemente** [comment]
Hm, instead of changing line 204, would changing line 150 to `this.known_languages.add( match[1].trim().toLowerCase() )` fix it?
`this.known_languages` should always have the languages lowercased.

**Comment by mcailleaux** [comment]
To complete this fix you have to change line 150 as you say and the line 32 with : 
let key = match[1].trim().toLowerCase();

**Comment by mclemente** [comment]
Do I still need to change line 204 or those two changes fix the problem?

**Comment by mcailleaux** [comment]
No need to change line 204, only those two changes are enough
