### ISSUE TITLE
[Suggestion] Make text and glyphs selectable

### ISSUE THREAD

**Issue by dmaneyapanda** [League-of-Foundry-Developers/fvtt-module-polyglot#88]
I'm not positive this is default behavior for Polyglot and not being caused by another mod, but sometime in the last month or so, anything being translated by Polyglot shows up as unselectable text, which means neither the glyphs for the "original" language nor the text for the translated version can be selected or copied.  Perhaps this is true only if "display translated box" is selected?  

It would be nice if this text, in particular the translated version, could be selected, for pasting into journal entries or other uses.

**Comment by mclemente** [comment]
> I'm not positive this is default behavior for Polyglot and not being caused by another mod...
> Perhaps this is true only if "display translated box" is selected?
> It would be nice if this text, in particular the translated version, could be selected, for pasting into journal entries or other uses.

Yes, it's the default behavior of the text in the translated box, without it, the text is selectable as normal, I'll change it to be selectable on the next update.
