### ISSUE TITLE
Tongues feature not working or am I just Dumb?

### ISSUE THREAD

**Issue by Mindblownlincoln** [League-of-Foundry-Developers/fvtt-module-polyglot#91]
So I was browsing through the settings and noticed the tongues feature of polyglot, and decided I needed to set it up for our monk. But testing it out it does not seem to work? Have I set it up wrong? The languages I have set up for it are as follows: 'Valekin Telepathy, Valevine Signs, Comprehend Languages, Tongues'.
Character With Tongues
![Charwithtongues](https://user-images.githubusercontent.com/80793771/111389187-875dba00-867e-11eb-8b1b-93d66c81936f.PNG)
Character Without Tongues
![charwithouttongues](https://user-images.githubusercontent.com/80793771/111389193-89c01400-867e-11eb-83ba-56351652e058.PNG)
Polyglot Settings
![Polysetting](https://user-images.githubusercontent.com/80793771/111389196-8b89d780-867e-11eb-9e0f-2aa72da63a04.PNG)

**Comment by mclemente** [comment]
Found the issue, I'll fix it on the next release. Meanwhile, a temporary solution is to also grant Comprehend Languages to the character.

**Comment by Mindblownlincoln** [comment]
Awesome, still better than what I was doing before. Thank you for your time.
